### ISSUE TITLE
Publishing (incl. Fehler)

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#100]
Ich werde immer mal wieder zwischendurch einen Testbuild laufen lassen (kann übrigens auch sonst jeder), um zu sehen, ob sich neue Probleme eingeschlichen haben.
Ergenisse kommen hier rein.

**Comment by MasterQ32** [comment]
> Can't open file: 'best_noise+10.tga'

Interessant, ich hab die Datei "best_noise_10.tga" im Projekt, aber ich finde keine Referenzen mehr auf die "best_noise+10.tga". Ne Idee, wo das herkommen könnte?

**Comment by firoball** [comment]
bestiary.wmp

**Comment by MasterQ32** [comment]
Müsste in commit e377f10ddd71a494c1bc9f9afd57f54a05facf09 behoben sein

**Comment by MasterQ32** [comment]
Habe die beiden anderen Build Errors ebenfalls behoben in commit 63138a1dc66469cfb4105110f61df5c90041dc99

**Comment by firoball** [comment]
Kein Buildfehler per se, und auch sonst passiert wenig, aber spammt die acklog voll: UI.c released seinen allokierten Speicher nicht korrekt.

**Comment by MasterQ32** [comment]
> UI.c released seinen allokierten Speicher nicht korrekt.
`UI.c` released überhaupt keinen Speicher, das ist "allocate once and keep" (ist also kein memory leak oder sowas). Falls das stört, kann ich da noch Energie rein investieren,  aber eigentlich isses egal.

> und auch sonst passiert wenig
Was heißt das genau? Spiel startet nicht?

**Comment by mk1x86** [comment]
Ich glaube, ihr missversteht euch. Es passiert nichts schlimmes, außer dass das Log vollgeschrieben wird. Alles ist gut, niemand wurde verletzt, da Energie reinstecken ist Resourcenverschwendung, weiter gehts!

**Comment by MasterQ32** [comment]
Da das thematisch hier rein passt:

Wir haben noch die HD-Textur für das Level, die wir ja aber grade nicht nutzen Aufgrund von WED. Man könnte doch in den Publish-Prozess nen Automatismus einbauen, der beim Publish immer die Textur vorher ändert...

@xwcg, was müsste man dafür denn ändern?

**Comment by firoball** [comment]
Im Endeffekt müsste man sie als .Pak einbinden, dann kann man sie durch kopieren ersetzen. Oder man kopiert den placeholder erst weg, die richtige Textur hin, und resourced dann... Also gehen müsste das eigentlichAm 11.07.2018 9:10 nachm. schrieb Felix Queißner <notifications@github.com>:Da das thematisch hier rein passt:
Wir haben noch die HD-Textur für das Level, die wir ja aber grade nicht nutzen Aufgrund von WED. Man könnte doch in den Publish-Prozess nen Automatismus einbauen, der beim Publish immer die Textur vorher ändert...
@xwcg, was müsste man dafür denn ändern?

**Comment by MasterQ32** [comment]
@ilegacy Kannst du mal den Atlas in HQ pushen, aber bitte in den ArtSource-Ordner, hab den grade vergeblich gesucht

**Comment by MasterQ32** [comment]
Habe in commit dde04c6cc1a51ef635e54dc2b05f52bc76eea2ae mal eine kleine Verbesserung gemacht:
Die `config.h` wird jetzt im Build mit einer leeren Datei ersetzt und anschließend die alte Datei wieder hergestellt. Damit kann man den Build nicht ausversehen mit Debug-Kram verschusseln

**Comment by firoball** [comment]
Sonntag Abend würde ich gerne einen Preview Build raushauen, damit wir zwecks finalem Balancing den Freundeskreis auch mal ranlassen und uns Feedback einholen können.

**Comment by MasterQ32** [comment]
Das Ziel würde ich auch anstreben, ist ja mittlerweile durchaus ziemlich weit

**Comment by firoball** [comment]
Im hinteren Abschnitt (Bereich Powercore und Gänge direkt davor) sind Mobs und Ammo/Health noch nicht wirklich platziert. Vielleicht hat da noch jemand Lust, ein wenig rumzuprobieren.
