### ISSUE TITLE
Lautstärke-Einstellungen für das Spiel

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#101]
Aufgesplittet in:
- Musik
- Effekte
- Sprache

**Comment by MasterQ32** [comment]
Jo, würde ich aber erst in nen späteren Release mit reinnehmen, weil man nochmal den kompletten Code anfassen muss

**Comment by mk1x86** [comment]
machen wir eh nicht mehr. für's nächste Projekt dann.
