### ISSUE TITLE
Dinge für den Release

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#103]
- Das Intro #104 
- Power core terminal (quasi copy paste vom engine terminal) #106
- Power core beams (copy paste engine beams) #106
- Release Build #100 
- Kollissionspatch mit Blöcken #112
- Batterieladestation mit Batterie #76
- Balancing #78

**Comment by MasterQ32** [comment]
Falls noch was an Features dazu kommt, bitte hier sammeln, damit man den Überblick behält und ne Diskussionsgrundlage hat

**Comment by firoball** [comment]
Hab die #40 oben dazueditiert

**Comment by MasterQ32** [comment]
Habe die #100 dazu editiert

**Comment by MasterQ32** [comment]
+ #112

**Comment by firoball** [comment]
#76

**Comment by firoball** [comment]
Ich kümmere mich um die hochauflösende Atlas Map.
Fehlt außer Artwork noch was zum Release? Ich habe nicht so recht den Überblick...

**Comment by mk1x86** [comment]
Ja, der power core room

**Comment by firoball** [comment]
mh... da kann ich eher wenig helfen. Optisch ist das ganze Ding deutlich über meinem Niveau... 🤣

**Comment by xwcg** [comment]
ja mach ich heute oder morgen noch

**Comment by firoball** [comment]
#78 hinzugefügt

**Comment by ilegacy** [comment]
Großes Lob, was habt ihr denn da noch alles eingebaut? Das ist ja super! Habe es gerade das erste mal durchgezockt. Hammer! :)
