### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#104]

**Comment by firoball** [comment]
Was genau soll im Intro passieren, ist das schon festgelegt?

**Comment by MasterQ32** [comment]
Wie in der [Story](https://github.com/Acknex/LotterShock/wiki/Story-Texte) beschrieben eine Cutscene mit zwei Einstellungen auf Lottis Raumschiff sowie der USS Patchnotes und währenddessen das Abspielen der Audiofiles...

Ich bin grade auch noch am überlegen, ob ich dafür nicht noch nen zweiten Style für die Journal-Einträge bastel, die dann "echte" Untertitel sind

**Comment by mk1x86** [comment]
Wäre gut, wenn man das unterscheiden könnte

**Comment by MasterQ32** [comment]
Joa, dann würde ich da einfach noch für den Journal-Eintrag einen Playback-Style anlegen, der definiert, wie  der Eintrag gezeichnet wird (Untertitel einfach über der HUD als weißer Text mit WWRAP und OUTLINE)

**Comment by firoball** [comment]
OMG. Das baut auf GotG auf?
Dann müssen wir ja Deadpool-like mit ner Zeitreise den falschen Lotti aus GotG rauspatchen 🤣

**Comment by mk1x86** [comment]
Okay, ich kapier gerade gar nichts. Starlotti trat zum ersten mal in Guardians of the Galep auf, was vom Namen her auf GotG basiert, ja.
Aber die Story jetzt gerade ist wohl eher Matrix/The 13th Floor

Und was hat da Deadpool mit zu tun?

**Comment by firoball** [comment]
Deaadpool hat beim zweiten Teil im Abspann den beschsisenen deadpool aus X-Men kurzerhand umgenietet 🤣 
Somit wurde die Inkonsistenz quasi beseitigt.

Und unser Original Star Lotti ist ja eigentlich ein Morbius, den wir aus der Not heraus in ne Suppenschüssel geklebt haben. Der gehört also im Intro "hochgepatcht" ;)

**Comment by mk1x86** [comment]
Aaaah 🤣 
Haben wir das nicht schon mit dem Poster abgedeckt?

**Comment by firoball** [comment]
Das Poster deckt eigentlich gar nix ab, bzw. war da keinerlei Hintergedanke diesbezüglich.

**Comment by mk1x86** [comment]
Das Poster im Spiel. Nicht das ackcon poster

**Comment by firoball** [comment]
Achso das... Finde ich zu abstrakt. Hätte ich nie in diese Richtung gedeutet, eher als Bonus spitze gegen jclAm 11.07.2018 7:23 nachm. schrieb mk1x86 <notifications@github.com>:Das Poster im Spiel. Nicht das ackcon poster

**Comment by firoball** [comment]
Aber ist letzten Endes auch egal. Das ist nur ein spontaner Gag, der mir eingefallen war Am 11.07.2018 8:21 nachm. schrieb Robert Jäger <robert@firoball.de>:Achso das... Finde ich zu abstrakt. Hätte ich nie in diese Richtung gedeutet, eher als Bonus spitze gegen jclAm 11.07.2018 7:23 nachm. schrieb mk1x86 <notifications@github.com>:Das Poster im Spiel. Nicht das ackcon poster

**Comment by MasterQ32** [comment]
Da noch nichts dazu im Repo ist, setze ich mich jetzt mal in der Bahn ran und hacke einen Prototyp des Intros zusammen

**Comment by firoball** [comment]
Ich bin gerade am Level dran wegen den Augenpfaden. FyiAm 12.07.2018 8:45 vorm. schrieb Felix Queißner <notifications@github.com>:Da noch nichts dazu im Repo ist, setze ich mich jetzt mal in der Bahn ran und hacke einen Prototyp des Intros zusammen

**Comment by xwcg** [comment]
> "Schmier-Effekt" (kp, wie ich das hinbiege, wird aber schon irgendwie klappen)

camera->alpha = 50;

**Comment by MasterQ32** [comment]
Tut das tatsächlich? Wäre ja richtig geil, wenn dem so ist!

**Comment by mk1x86** [comment]
hängt damit natürlich extrem von der Framerate ab. Aber ja, tut tatsächlich

**Comment by MasterQ32** [comment]
Habe das Intro jetzt mal hochgeladen. Ist grafisch noch nicht wirklich eine Schönheit, aber funktional isses.

**Comment by ilegacy** [comment]
Haha das ist ja super! Ein richtiges Intro mit Story und allem. Sehr geil! <3

**Comment by firoball** [comment]
Ist das Intro schon in finaler Geschwindigkeit?
Ich finde, man muss da irgendwie auf Steroiden sein, um bei der Geschwindigkeit den Texten folgen zu können ⏩

**Comment by MasterQ32** [comment]
Ne, da fehlt grade noch der Audio-Schnitt :sound: von @mk1x86. Afaik ist das aber alles schon eingesprochen

**Comment by mk1x86** [comment]
bin quasi gerade dran

**Comment by mk1x86** [comment]
Schnitt ist jetzt fertig. An einer Stelle hört man's, aber das geht leider nicht anders. :-(

**Comment by firoball** [comment]
Cool, langsam kann mans erahnen :)
der zweite Teil soltle idealerweise erst anch dem Loading Screen gestartet werden... so wirkt es irgendwie etwas seltsam.
Wenn man den ersten Teil überspringt, überlappen sich der noch angefangene Rest von Teil1 mit dem Anfang von Teil 2.

**Comment by MasterQ32** [comment]
> Wenn man den ersten Teil überspringt, überlappen sich der noch angefangene Rest von Teil1 mit dem Anfang von Teil 2.

Was überlappt da denn genau?

> der zweite Teil soltle idealerweise erst nach dem Loading Screen gestartet werden... so wirkt es irgendwie etwas seltsam.

Die ersten beiden Szenen sind ja in einem Außenlevel, da sollte man imho nicht das Hauptlevel reinladen

**Comment by firoball** [comment]
Einfach am Anfang eines langen Samples abbrechen, dann wird das noch abgespielt, während das Level schon geladen wurde und der zweite Teil des Intros beginnt. Das haut ja schon während dem Ladescreen die ersten Samples raus, und somit überlagern sieAm 17.07.2018 8:09 vorm. schrieb Felix Queißner <notifications@github.com>:
Wenn man den ersten Teil überspringt, überlappen sich der noch angefangene Rest von Teil1 mit dem Anfang von Teil 2.

Was überlappt da denn genau?

der zweite Teil soltle idealerweise erst nach dem Loading Screen gestartet werden... so wirkt es irgendwie etwas seltsam.

Die ersten beiden Szenen sind ja in einem Außenlevel, da sollte man imho nicht das Hauptlevel reinladen

**Comment by mk1x86** [comment]
So, habe im Intro noch das Schiff und die Textur ausgetauscht. Irgendwie wird aber von der USS Patchnotes keine Lightmap angezeigt und es hat diesen bloom shader. Kann man das irgendwie wieder normal anzeigen lassen (zumindest mit Schatten)? Da bin ich zu sehr raus.

**Comment by mk1x86** [comment]
Gar keins. Ist einfach ein Block

**Comment by firoball** [comment]
es ist wohl noch irgendein PP shader aktiv. Muss sich vielleicht @MasterQ32 mal anschaun. Die Lightmap vom patchnotes Block nimmt er einfach nicht mit.

**Comment by MasterQ32** [comment]
Ich hab jetzt mal nen Shader für Blocks gemacht, der keinen Glow-Effekt hat, aber bei Lightmapping bin ich leider raus, wie man das hinbekommt...
Könnte man da nicht einfach irgendein passendes LIGHT-Sprite davor setzen?

**Comment by MasterQ32** [comment]
Ich würde das Intro jetzt so lassen, es sieht ohne Glow wesentlich weniger Scheiße aus als mit...
Die PP-Pipeline ausschalten ist nicht so trivial, die betrifft jegliche geladene Modelle und Materials, wenn du PP ausschalten würdest, hätten wir nur noch Glow-Effekte, aber kein diffuses Lighting mehr (also genau das Gegenteil von dem, was wir wollen)

**Comment by firoball** [comment]
Hm... können wir das Ding als Map Entity machen und dann per Script mtl_shaded (default Block Material) zuweisen? Also sprich nur Default materials verwenden, die ja nicht in usnerer Pipe drinhängen (sollten)?

Ansonsten - ja. Bevor der Aufwand ausartet, lassen wirs so. Evtl. dann die Textur nochmal ohne "USS Patchnotes" und den Block splitten, damit sich der Schriftzug wenigstens nicht wiederholt.

**Comment by MasterQ32** [comment]
Die Pipeline hat alle Standard-Materials mit einem Shader überladen, sonst müsstest du jedem Objekt im Level manuell ein nondefault-Material zuweisen...

Das mit dem Block Splitten würde ich machen, das sollte ja auch schon ausreichen von der optik

**Comment by firoball** [comment]
Ah, ich hab mich schon die ganze Zeit gewundert, wie das mit dem Level Shader funzt ;) Again what learned. Dann Block split und aus die Maus.

**Comment by MasterQ32** [comment]
Hab den Blocksplit in commit f6d95aee8553415f060de673daf02a768283d16e gemacht, sieht so jetzt ganz anständig aus
