### ISSUE TITLE
Trigger für die acktana dialoge

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#105]
Aufbauen auf den Journal-Einträgen sollten noch die Dialoge zwischen StarLotti und Acktana abgespielt werden können

**Comment by MasterQ32** [comment]
Gibt jetzt eine Funktion `void journals_play(int id)`, welche verwendet werden kann, um Journale manuell zu triggern. Zudem können Journale jetzt einen Followup haben, mit dem man einen Dialog bauen kann

**Comment by MasterQ32** [comment]
Habe in commit ddf626fbbc2967b088029c3d5af321d4021d52d3 mal alle Story-Dialoge aus dem Wiki eingebaut sowie eine Callback-Option auf dem letzten Dialog, der theoretisch das Spiel beenden kann

**Comment by MasterQ32** [comment]
Ich würde heute Abend mal die komplette Ingame-Story vollends einbauen, ggf. auch mit Platzhaltern und ähnlichem, einfach damit der Code dafür auch da ist

**Comment by MasterQ32** [comment]
Habe mit commit b5708d9eec1490e6d0afa1a5defbc7e995e777a8 nun alle Story-Trigger im Spiel platziert, die auf der Wiki-Seite standen, fehlen noch die Audio-Files dafür @mk1x86

**Comment by mk1x86** [comment]
Matrix bed interaktion. Ein Takt von @xwcg und Acktana (bekomme ich morgen)

**Comment by mk1x86** [comment]
done
