### ISSUE TITLE
Power core terminal 

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#106]
- Power core terminal (quasi copy paste vom engine terminal)
- Power core beams (copy paste engine beams)

**Comment by MasterQ32** [comment]
@sgpohl Du hast da ja schon mal was gebaut... Wie viel ist davon einsatzbereit?

**Comment by MasterQ32** [comment]
Habe jetzt einen Dummy-Trigger in den Power Core Room gestellt, um den Spielfluss zu komplettieren, fehlt noch ein hübsches Level drumrum

**Comment by firoball** [comment]
Kriegen wir das irgendwie mit wenig Aufwand noch "hingeschustert"? Ich habe etwas Sorge, dass uns die Puste ausgeht, und das Release nix wird :/

**Comment by xwcg** [comment]
wie schon anders erwähnt, mache ich noch

**Comment by mk1x86** [comment]
Wie gesagt, habe jetzt Urlaub und kann abends was machen. Hab Geduld
