### ISSUE TITLE
Spiel end trigger

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#107]

**Comment by firoball** [comment]
Thema Spielende... wieviel Arbeit wollen wir da noch reinstecken?
Ist ein "You did it" Screen ausreichend, oder kommt das zu ranzig rüber?

Man könnte ihn mit nem hübschen Artwork versehen... falls da jemand Lust zu hat.

**Comment by MasterQ32** [comment]
@mk1x86 schlug diesen Pixelizer-Effekt vor, was ich als Fadeout auf jeden Fall nicht schlecht finde...

Was man n bisschen zum Trollen machen könnte, wäre ein "You did it" mit "The story continues in 'Lotter vs. the World'" und dann von dem Spiel ein paar Screenshots reinfaden

**Comment by firoball** [comment]
Der pixelizer funktioniert leider nicht für die Waffen. Aber gut, die kann man auch vorab ausblendenAm 09.07.2018 2:19 nachm. schrieb Felix Queißner <notifications@github.com>:@mk1x86 schlug diesen Pixelizer-Effekt vor, was ich als Fadeout auf jeden Fall nicht schlecht finde...
Was man n bisschen zum Trollen machen könnte, wäre ein "You did it" mit "The story continues in 'Lotter vs. the World'" und dann von dem Spiel ein paar Screenshots reinfaden

**Comment by mk1x86** [comment]
Waffe ausblenden, Effekt auf den Text, den Lotter am Ende sagt. und zum Schluss so ein "Auschalt"-Shader, wo das Bild zusammenklappt und kurz aufblitzt (wie die alten Röhrenfernseher).

Außerdem im Intro den Text "40 minutes before the Guardian incident" oder so

**Comment by MasterQ32** [comment]
@mk1x86 klingt gut, an was für einen Effekt hattest du da bei dem Text gedacht?

**Comment by mk1x86** [comment]
geringer sample-rate, weniger bit depth. Wie bei Matrix die Spiegel/Aufwach-Szene

**Comment by MasterQ32** [comment]
Ich hatte grade **die** Idee im Zug:

1. Man klickt das "Bett" an
2. Kamerafahrt, die quasi ein "Reinsetzen" andeutet
3. Szene wird mit einem Effekt zur Matrix, in der man den Guardian in ASCII sieht und ein Lachen hört
4. Röhren-Ausschalt-Effekt
5. Stille
6. Roll Credits

Meinungen?

**Comment by MasterQ32** [comment]
Auch mal ins offizielle Log: Es geht voran!

Habe jetzt die Kamerafahrt sowie den Matrix-Effekt implementiert, der Guardian taucht dann nach kurzem Matrix-Geflimmer in der Matrix auf.

@mk1x86 Kannst du für einen "fiese Lache"-Sound sorgen und ggf. so einen "jack in"-sound oder soll ich da mal freesound foltern?

**Comment by mk1x86** [comment]
ich mach schon. sehr wahrscheinlich noch heute Abend

**Comment by MasterQ32** [comment]
Habe in commit c4e07da55a63a5c4b413434a0613996b3d372c51 die grafischen Effekte eingebaut, werde die Sounds nachrüsten, sobald ich wieder Sound habe (ist unterwegs immer n bisschen schlecht) ^^

**Comment by MasterQ32** [comment]
Sollte jetzt mit Musik und allem drum und dran abgespielt werden, Spiel ist jetzt offiziell durchspielbar!
