### ISSUE TITLE
PDA Text bleibt hängen

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#108]
Irgendwie hab ich das hingekriegt. Da ich den Text nicht abbrechen konnte, bin ich einfach weitergelaufen und hab weitergespielt. Dabei scheint irgendwas den Timeout der PDA Anzeige zu grillen.
![shot_0](https://user-images.githubusercontent.com/4692010/42422425-db54221a-82e5-11e8-9b8e-9fc624b43510.jpg)

**Comment by MasterQ32** [comment]
Huh, das ist ja absurd. Hattest du noch Audio laufen? Oder war das vorbei?

**Comment by firoball** [comment]
Das war lange durch

**Comment by MasterQ32** [comment]
Kam irgendeine Fehlermeldung oder ähnliches?
Ich kann mir das grade nicht so wirklich erklären, da müsste dann `media_playing` für das `journals_mediahandle` 1 zurückliefern, der Wert vom `journals_mindelay` ist ja definitiv kleiner 0

**Comment by firoball** [comment]
Ne kam garnix. Ist einfach nur dieser Debug Counter weiter nach unten gelaufen.

**Comment by firoball** [comment]
Am besten einen easy fix: absolutes Timeout. Aus die Maus.

**Comment by MasterQ32** [comment]
Hm, ich möchte halt auf jeden Fall den kompletten Journal-Eintrag abspielen lassen, von daher sollte ich auf das media_playing achten...

Und inwiefern absolutes Timeout? Ich setze ein Timeout beim Start des Journals und warte dann, bis es abgelaufen ist.

Konnte das Problem tatsächlich auch einmal reproduzieren, aber ich hab ehrlich gesagt keine Ahnung, wie das geklappt hat

**Comment by firoball** [comment]
Was ich meinte: Zeit über media_playing abfragen. Unabhängig davon nen Coutner mitlaufen lassen, und den bei... kA... 20 oder 30 Sekunden das Ding zuamchen lassen. Dann ist das nicht ideal, aber irgendwann gehts weg.

evtl. haben wir auch zuviele Sounds laufen und media_playing geht lottermäßig den Bach runter 🤣

**Comment by MasterQ32** [comment]
Also, ich bekomms reproduziert:
Das ganze tritt auf, wenn man das Spiel pausiert und wieder entpausiert, danach ist der Zustand von `media_playing` broken... Einmal media_pause und media_start aufgerufen, dann geht es wieder

**Comment by firoball** [comment]
bei mir ist das nicht mehr vorgekommen. Ich mach das mal zu.

**Comment by MasterQ32** [comment]
Jop, bei mir ist es wieder vorgenommen... Was für ein Krampf

**Comment by firoball** [comment]
Siehe Vorschlag oben. Harten Timeout rein als letzten Fallback (oder ne Möglichkeit, das Journal "wegzuklicken"), und Future Release als Milestone für die Issue setzen.
Wird Zeit, dass wir zum Ende kommen.

**Comment by MasterQ32** [comment]
Jo, setz ich heute Abend um

**Comment by MasterQ32** [comment]
Habe ein hard-limit auf 60 Sekunden in commit d279c5b9b90e9b5eedca4aa5415954b3b1988fac implementiert.
