### ISSUE TITLE
Beastiary: Voices direkt freigeschalten

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#111]
Wie der Titel schon sagt.
Hat man noch keine Viecher freigeschalten, kriegt man zwar nix angezeigt, aber die Stimme plaudert fröhlich schon alles aus.

**Comment by MasterQ32** [comment]
Ja, da guck ich morgen im Zug danach... Ich würde die Sprachausgabe eh um mind. 0.5 Sekunden verzögern, vielleicht sogar ne Ganze

**Comment by mk1x86** [comment]
Nicht drüber nachgedacht, sry

**Comment by MasterQ32** [comment]
Fixed in commit 0660c03a693fbe4bd24ff88bc5a97dbad2cf3d94
