### ISSUE TITLE
Eselslerchennormalmapsky

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#113]
![shot_0](https://user-images.githubusercontent.com/4692010/42735716-5183619e-8859-11e8-84b2-59bccb9cfa41.jpg)
Sieht irgendwie nicht so aus, als gehört das so 🤣 ... oder soll das ein Placeholder sein?

**Comment by firoball** [comment]
Sky cubes entfernen sich nicht mit entladen des Levels, deren Textur aber schon!?
Fixed. 
#dankejcl

**Comment by MasterQ32** [comment]
Watn Krampf, danke fürs fixen!
