### ISSUE TITLE
Evoke 2018

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LotterShock#116]
Heyhey!
Ich werde das Spiel mal auf der Evoke 2018 in der Interactive Compo releasen, da haben wir noch ein bisschen Audience
https://www.evoke.eu/2018/competitions/#interactive

**Comment by firoball** [comment]
Gern... nur...

> Must not have been released before.

Das könnte ein Problem sein :|

**Comment by ikskuh** [comment]
Hab ich geklärt, das ist "kein Problem" ^^

**Comment by firoball** [comment]
Na dann auf auf <3

**Comment by firoball** [comment]
Brauchst du noch irgendwas zur Präsentation?

**Comment by ikskuh** [comment]
Nö, eigentlich nicht. Bin nur am überlegen, wie man es präsentiert.... :) Aber da wird mir bis heute Abend sicher noch was einfallen

**Comment by firoball** [comment]
ein Greetings Scroller noch irgendwo eingebaut wäre halt imho bei so nem Event mandatory. Aber ich wüsste auch nicht, wen wir grüßen sollen :D

**Comment by firoball** [comment]
Ich hab grad gesehen, irgendwas ist mit dem Lighting im Beastiary kaputt, wenn man zuvor im Spiel war. Am besten das Beastiary also davor und dann nie wieder zeigen xD

Ansonsten würde ich vorschlagen, das Plakat als Aufhänger zu nehmen, und zumidnest das Teamfoto zeigen zur Vorstellung der Beteiligten. Vielleicht in ein/zwei Sätzen zusammenfassen, was es mit "AckCon" und diversen Anspielungen auf sich hat, und dann ab die Post.

**Comment by ikskuh** [comment]
> Wir grüßen JCL, J. Lotter, Johann L., ...

**Comment by mk1x86** [comment]
Geht's Punkt 22h los?

**Comment by firoball** [comment]
Der Stream läuft die ganze Zeit, wenns ne Verschiebung gibt, wird das eingeblendet oder gesagt.
https://www.evoke.eu/2018/live/

**Comment by firoball** [comment]
Platz 3. Closed.
