### ISSUE TITLE
Show Journal

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LotterShock#15]
Text anzeigen
Sound abspielen

**Comment by MasterQ32** [comment]
@padmalcom, @xwcg habt ihr die journals eigentlich schon im spiel bzw. wie kann man die auslösen?

**Comment by xwcg** [comment]
noch keine im level, aber so wie ich das sehe, nem ding die action  journal geben und den skill1 entsprechend auf die ID setzen

**Comment by MasterQ32** [comment]
Bin noch dran, habe jetzt mal eine verbesserte Version in commit c542befdf50c43be11f8fc172b1c7a60bd596d6d hochgeladen, erbitte Feedback!

Der Name fehlt grade noch, den könnte man noch anzeigen. Wollen wir da auch nen Bild der Person reinmachen oder wäre das doch n bisschen zu sehr Overkill? Würde halt schon zur Restqualität des Spiels passen

**Comment by mk1x86** [comment]
Kein Bild. Dann haben wir nämlich das Problem, dass wir keine Uniform oder ähnliches haben

**Comment by MasterQ32** [comment]
> Dann haben wir nämlich das Problem, dass wir keine Uniform oder ähnliches haben

Uniformen haben wir doch schon in Massen in den einzelnen Zimmern...

**Comment by MasterQ32** [comment]
Journal hat ab commit 685fc0a9a2b241b1e9d7490658d63cd0bcf92fb2 eine Namensanzeige und ab commit bffac2de59867f75149a84e518be071fc20b47a6 wird das Journal pausiert, wenn man ins Pausemenü geht.

Sehe die Sache hiermit als erledigt an.

**Comment by xwcg** [comment]
Jetzt spielt er aber immer dasselbe journal ab
