### ISSUE TITLE
Fliegendes Auge

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LotterShock#19]

**Comment by MasterQ32** [comment]
Wir haben ein Auge, das einen Pfad abfährt, kann man meiner Meinung nach schließen

**Comment by firoball** [comment]
Ich komme heute nicht mehr dazu. Würde mich aber gerne noch diese Woche dran probieren.

Schonmal eine Anleitung zum Platzieren in WED (im Zweifelsfall ist es dann am Ende Fluff :D ): @xwcg 

- Pfad in WED platzieren, als Name eine Zahl einstellen
- Eye mit Action "Eye" in WED paltzieren (egal wo)
- folgende Skills setzen:
EYE_PATHID: Id entsprechend Pfadname
EYE_PATHPROGRESS: 0-100, Startposition auf Pfad in %

**Comment by firoball** [comment]
Auf jedem Pfad können auch mehrere Augen unterwegs sein, aber dann sollte EYE_PATHPROGRESS unterschiedlich gesetzt sein

**Comment by mk1x86** [comment]
Ich würde das gerne mal pushen. Arbeitet da noch wer dran? Mir sind Gegner nämlich eigentlich wichtiger als irgendein Retropixellook

**Comment by firoball** [comment]
Ich hatte das Gegner fixing hochpriorisiert. Der turret war ein nebenherprojekt, das ich schnell umschreiben konnte.Die Augen hab ich noch auf der To-Do ListeAm 04.07.2018 12:53 nachm. schrieb mk1x86 <notifications@github.com>:Ich würde das gerne mal pushen. Arbeitet da noch wer dran? Mir sind Gegner nämlich eigentlich wichtiger als irgendein Retropixellook

**Comment by mk1x86** [comment]
Ok. Weil ich habe gerade etwas Angst, dass sich das nächste Woche im Sande verläuft, wenn die Motivation so langsam flöten geht und irgendwie kommen immer mehr Issues als dass es weniger werden

**Comment by firoball** [comment]
Wie bereits woanders geschrieben. Zur Not bleibt das Auge creepy fluff, wenn die Zeit ausgeht. Möchte aber nochmal dran arbeitenAm 04.07.2018 4:40 nachm. schrieb mk1x86 <notifications@github.com>:Ok. Weil ich habe gerade etwas Angst, dass sich das nächste Woche im Sande verläuft, wenn die Motivation so langsam flöten geht und irgendwie kommen immer mehr Issues als dass es weniger werden

**Comment by Hen-woll** [comment]
das Auge hat von mir vor einigen Tagen eine Animation erhalten, diese kann verwendet werden /Animations name [Stand]

**Comment by MasterQ32** [comment]
Dem Auge fehlen gerade irgendwelche Modelle, wenn es einen versucht, anzugreifen. Das ist beim Testen n bisschen nervig...

**Comment by firoball** [comment]
Auge kann jetzt gekillt werden.

Am Angriffscode hatte irgendwer anders rumgedoktort und eine Neuimplementierung gestartet, daher arbeite ich an meinem "Laserversuch" erstmal nicht weiter. Den Angriff habe ich rauskommentiert, weil es dauernd Fehlerpopups gab. Bitte fixen und wieder reinnehmen.

**Comment by mk1x86** [comment]
Komme wahrscheinlich erst Montag oder Dienstag dazu.

**Comment by firoball** [comment]
ich bastel die Attacke. Dann kannst du dich um die noch fehlenden Augengeräusche kümmern.

**Comment by firoball** [comment]
So, morgen hab ich ne längere Bahnfahrt, da möchte ich die Mobs dann komplatt abschließen.
Da kann ich dann wenigstens mal länger als ne Stunde am Stück werkeln.

**Comment by firoball** [comment]
Ich denke das passt sobald die Sounds drin sind. Die sind noch nicht fertig soweit ich weißAm 12.07.2018 11:26 nachm. schrieb Felix Queißner <notifications@github.com>:Die Attacke ist ziemlich fancy geworden, aber ich muss sagen, mir hat das Auge als reiner Fluff mehr gefallen, auch wenn ich die Platzen-Animation absolut geil finde splotsch.
Mir fehlt aber irgendwie noch ein guter Marker, wann das Auge tatsächlich tot ist, ich hab schon viel zu oft ne Portion Schrot zu spät draufgeballert...
Eventuell könnte man da was mit LIGHT und Rot werden basteln

**Comment by mk1x86** [comment]
Ja, mach ich noch
