### ISSUE TITLE
Shoot Code

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LotterShock#2]
Schießen
Waffenwechsel
Sounds
Trace UND Projektile
Melee
Querschläger bei Schrottflinte

**Comment by MasterQ32** [comment]
> commit 2f28b0eccddd1b378a4afd8b689cc718e32648c8
> Tried to make flamethrower better and failed

@xwcg story of my life

**Comment by MasterQ32** [comment]
Hab jetzt mal ne Änderung in commit bbe950643f98bc1ee1e3c97c20cb2610b962dd23 gemacht, fühlt sich jetzt vom Schaden und Feedback besser an.

@firoball Die Eselslerche bekommt jetzt auch keinen Knochback von den Flammen mehr, aber ich bitte dich:
```c
ptr->DAMAGE_VEC = nullvector;
```
Ich schiebe das mal auf die späte Uhrzeit und Bier :tongue:

**Comment by firoball** [comment]
Quotenbug. Such mal systematisch alle Files danach durch. Das hab ich öfter gemacht.

**Comment by MasterQ32** [comment]
Ne, sieht ansonsten anständig aus, gabs nur an zwei Stellen

**Comment by MasterQ32** [comment]
Waffen funktionen, schließe das Ticket
