### ISSUE TITLE
Hauptmenü

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#23]

**Comment by mk1x86** [comment]
@MasterQ32 noch was offen? sieht für mich gut aus

**Comment by MasterQ32** [comment]
Jain, ich hab da grade noch ein "Secret Project", aber grundlegend ist das Hauptmenü fertig und das Feature hat damit nur bzgl des Menüpunktes zu tun, also: ja, fertig.

**Comment by MasterQ32** [comment]
Habe die Animationen im Hauptmenü im letzten Commit zerstört, fixe das ebenfalls Freitag. Wollte schon vor ner Stunde aufhören, dafür haben wir jetzt ne coole Unlock-Mechanik für Elemente im Bestiary...

**Comment by firoball** [comment]
Das Rot vom beastiary Button ist minimal anders. Ich weiß, das ist sowas von egal, aber es nervt mich bei jedem einzelnen start 😂Ich wäre ein guter MonkAm 05.07.2018 12:51 vorm. schrieb Felix Queißner <notifications@github.com>:Reopened #23.

**Comment by MasterQ32** [comment]
Ja, mich triggert das falsche Rot auch, könnte @Hen-woll ja nochmal anpassen, wenn er fürs Bestiary das Panel macht

**Comment by MasterQ32** [comment]
Wurde angepasst
