### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#24]

**Comment by MasterQ32** [comment]
"Doku" findet sich in https://github.com/Acknex/LotterShock/wiki/Credits

**Comment by MasterQ32** [comment]
Ich merke an: Wenn wir fertig bzw. auf Final-Grafik sind, sollte man die Screenshots nochmal neu erstellen. 
@Acknex/ackcon-17 : Man könnte da auch noch Fotos von der AckCon reinpacken, wenn das allgemeine Zustimmung findet

**Comment by mk1x86** [comment]
https://cloud.simont.de/public.php?service=files&t=36631d031498473a72f0793945db845d

Und ja, nur ein Gruppenfoto

**Comment by ilegacy** [comment]
Ich kann ein Gruppen-Foto mit Photoshop machen, auf dem wir alle drin sind. Derzeit fehlt immer der Kamera mann.

Übrigens braucht ihr bei mir nicht Art-Direction hinschreiben. Das stimmt ja auch gar nicht. Ich hab einfach das Level gemacht :)

**Comment by firoball** [comment]
Am besten noch auf das Gruppenfoto von @ilegacy warten und reinkleben. Ansonsten lohnt es sich evtl. einige Screenshots zu aktualisieren. Der Secret Room und die Eselslerche z.B. sehen mittlerweile ja komplett anders aus.
Es würde außerdem Sinn machen, wenn nach Ablauf der Credits automatisch wieder ins Hauptmenü gewechselt wird. Das ist zwar absolut nicht tragisch, aber wäre noch hübsch.

**Comment by MasterQ32** [comment]
>Es würde außerdem Sinn machen, wenn nach Ablauf der Credits automatisch wieder ins Hauptmenü gewechselt wird. Das ist zwar absolut nicht tragisch, aber wäre noch hübsch.

Wird es doch, sobald Text als auch Musik durchgelaufen ist, landet man wieder im Hauptmenü (außer `media_playing` zickt auch hier ^^)

**Comment by firoball** [comment]
Hmm... Also entweder ist die Musik ne ganze Weile silent, oder bei mir funktioniert das nicht (nie, auf zwei Rechnern)Am 17.07.2018 8:06 vorm. schrieb Felix Queißner <notifications@github.com>:
Es würde außerdem Sinn machen, wenn nach Ablauf der Credits automatisch wieder ins Hauptmenü gewechselt wird. Das ist zwar absolut nicht tragisch, aber wäre noch hübsch.

Wird es doch, sobald Text als auch Musik durchgelaufen ist, landet man wieder im Hauptmenü (außer media_playing zickt auch hier ^^)

**Comment by MasterQ32** [comment]
> Hmm... Also entweder ist die Musik ne ganze Weile silent, oder bei mir funktioniert das nicht (nie, auf zwei Rechnern)

Grade nochmal getestet. Lied lief durch, Text lief kurz vorher durch, fadeout, Hauptmenü kommt

**Comment by firoball** [comment]
Ich habs nochmal auf nem anderen Rechner probiert - da gehts.
Ist irgendwas mit meinen Kisten anscheinend.
Da man auch manuell beenden kann ist das untragisch.

**Comment by firoball** [comment]
@ilegacy bitte das zurechtgeshoppte Gruppenfoto mit allen ins Artsource einchecken, damit es in die Credits eingebaut werden kann. Danke.

**Comment by ilegacy** [comment]
@firoball ist in artsource als "gruppenbild.png" hochgeladen :)

**Comment by MasterQ32** [comment]
Die neuen Screenshots mach ich morgen

**Comment by MasterQ32** [comment]
Neue Screenshots mit leichter Nachbearbeitung für die Credits in commit 9047d4f85d9fe5647ee11c4ca656947b340cebe1

Damit würde ich die Credits abschließen
