### ISSUE TITLE
Enemy sounds

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#31]

**Comment by MasterQ32** [comment]
@xwcg ist das hier noch aktuell oder kann das weg?

**Comment by xwcg** [comment]
kann weg glaub ich

**Comment by mk1x86** [comment]
Das Auge hat noch keine Schmerzen, oder?

**Comment by firoball** [comment]
Schmerzen ja, aber es schreit nicht wie am Spieß 😃Am 07.07.2018 10:32 vorm. schrieb mk1x86 <notifications@github.com>:Das Auge hat noch keine Schmerzen, oder?

**Comment by firoball** [comment]
Auge wird mit #19 weiterverfolgt.
