### ISSUE TITLE
Out-of-bounds

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#36]
Man kann sich immer noch recht schnell out-of-bounds glitchen in diesen komischen Fenstern:

Da mir das grade ausversehen beim Erkunden passiert ist, wollte ich das nochmal ansprechen (Bin in der Kantine nach oben gehüpft und dann in der Wand festgesteckt

![](https://puu.sh/APkbb/6c7313fbb3.png)

Was man eventuell machen könnte, wäre einfach eine unsichtbare Plane (alpha=0) vor das Fenster zu packen, mit der man aber noch kollidiert, das müsste das Problem beheben

**Comment by firoball** [comment]
Da auch die Eselslerchen genau diese Probleme haben, macht es vermutlich Sinn, sobald das Level fertig designed ist, im Schichtwechsel none-Blocks reinzuwurschteln. Fire and froget oder so.

**Comment by ilegacy** [comment]
Ich habe mal einen test gemacht und beim Küchen-Fenster-Segment die Polys dupliziert und ein bisschen nach hinten geschoben. Sehr hässlicher hack. Eine "richtige" Collision wäre schon besser, aber wenn @xwcg die Küche neu ins Level importieren kann, könnten wir mal testen ob es den Glitch vermeidet.

**Comment by firoball** [comment]
Zumindest für die Eselslerchen habe ich noch eine Idee, die ich relativ zügig austesten kann. Da das Zusammenspiel von c_move und Meshes ja scheinbar ne einzige Katastrophe ist, habe ich überlegt, eine Front-Abstandsmessung per zusätzlichem c_trace einzubauen, damit im Zweifelsfall eine Bewegung in die Wände aufgehalten wird. 
Erfolgsaussicht ist aber zweifelhaft, da c_move denke ich mal intern auch nur c_trace verwenden wird.

**Comment by mk1x86** [comment]
Geht so. c_move sollte eigentlich einen Ellipsentest machen

**Comment by firoball** [comment]
Ich hab den Eselslerchen  mal testweise einen c_trace for den c_move gehängt. Bitte beim Testen mal ein Auge drauf haben, ob sie damit weniger glitchen...

**Comment by firoball** [comment]
Also es gäbe noch eine Maßnahme, die das Railhooking bessert (nicht ganz beseitigt, aber bessert), allerdings ist das wohl etwas eklige und zeitintensive Fleißarbeit...
Es bräuchte im Endeffekt "Leitpfosten" immer an den Geländerenden, damit die Mobs um die Ecke gliden können und sich nicht an der Ecke vom Geländer festbeißen. Oder kann man das vielleicht sogar direkt noch in die Modelle integrieren?

![shot_0](https://user-images.githubusercontent.com/4692010/42478728-125489b2-83d6-11e8-8381-e1a65edb88f3.jpg)

**Comment by xwcg** [comment]
Vor dem publishen werden da überall noch unsichtbare blocks als collisionmodel dazu kommen, also ich glaube dass problem kann man ab jetzt ignorieren

**Comment by firoball** [comment]
Für das Level gibt es eine separate Issue #112. Kann zu.
