### ISSUE TITLE
Spielelizenz

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#37]
Wollen wir das Spiel unter eine vernünftige Open-Source-Lizenz stellen ([WTFPL](https://de.wikipedia.org/wiki/WTFPL) zum Beispiel)?

Damit wäre der Kram für Gamestudio auch eine Bereicherung

**Comment by mk1x86** [comment]
Wenn, dann bitte CC-0

**Comment by MasterQ32** [comment]
Joa, macht schon Sinn

**Comment by firoball** [comment]
https://creativecommons.org/publicdomain/zero/1.0/legalcode

**Comment by firoball** [comment]
Lizenzdatei ist angelegt. Fürs erste mach ich hier zu.
