### ISSUE TITLE
ent_preload testen

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#39]
Ich denke die Ruckler kommen wegen den Ladepausen beim Erstspawn der Entities. Die Eselslerche spawnt verschiedene Decals und Gib Modelle.

Reminder: ent_preload austesten

**Comment by MasterQ32** [comment]
Hab `preload_mode` schon aktiviert und es hilft ein bisschen. Ich hab ne bescheurte Idee, wie man das Decal-Laden beschleunigen kann:
Wir bauen einfach einen Raum in das Level, in dem einmal im ersten Frame beim Laden alle Splatter-Effekte ausgelöst werden

**Comment by firoball** [comment]
Zumindest für die Gib Modelle. Die werden per String geladen, das kapiert preload_mode nicht. Und ich bin mir nicht sicher ob pragma_pack hilftAm 02.07.2018 12:43 nachm. schrieb Felix Queißner <notifications@github.com>:Hab preload_mode schon aktiviert und es hilft ein bisschen. Ich hab ne bescheurte Idee, wie man das Decal-Laden beschleunigen kann:
Wir bauen einfach einen Raum in das Level, in dem einmal im ersten Frame beim Laden alle Splatter-Effekte ausgelöst werden

**Comment by xwcg** [comment]
Ich hab mit 11b00e1 eben nen gib-raum eingebaut, damit explodieren die viecher zumindest ohne ruckeln, das erste mal anschießen hackt aber immernoch wegen den splattern

**Comment by firoball** [comment]
Schau Mal was in der splatter_splat in Splatter.c gespawnt wird und wirf das falls möglich mit reinAm 02.07.2018 1:30 nachm. schrieb Michael Schwarz <notifications@github.com>:Ich hab mit 11b00e1 eben nen gib-raum eingebaut, damit explodieren die viecher zumindest ohne ruckeln, das erste mal anschießen hackt aber immernoch wegen den splattern

**Comment by xwcg** [comment]
hats nicht wirklich verbessert, zappelt immernoch beim ersten schießen

**Comment by firoball** [comment]
Dann den weapon Code nach Partikeln und Effekt ents untersuchenAm 02.07.2018 1:44 nachm. schrieb Michael Schwarz <notifications@github.com>:hats nicht wirklich verbessert, zappelt immernoch beim ersten schießen

**Comment by firoball** [comment]
Also mit dem Decal preloading ist es meiner Meinung nach jetzt absolut in Ordnung. Issue kann zu.
