### ISSUE TITLE
Readme.txt

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#40]
Ist noch etwas inhaltslos.

**Comment by MasterQ32** [comment]
Ich bau mal n bisschen an der Readme, damit da was hübsches drinsteht

**Comment by MasterQ32** [comment]
Habe in commit eeb44e88a9bf26e6a0aaffd57ad2978e67aedab8 mal n bisschen was geschrieben, ist auf jeden Fall besser als nix

**Comment by firoball** [comment]
Use noch mit 'E' angeben und dann passts :)

**Comment by MasterQ32** [comment]
Done in commit 96cc8fdf1af94c8d380703070cd73c86a8f46f98
