### ISSUE TITLE
Keine Decke im kantinen eingang

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#43]
Das kleine stück bei der kantine/küche bis zu türrahmen hat keine decke

**Comment by ilegacy** [comment]
re-exported :)  kannst du es neu ins MDL gießen? danke!

**Comment by ilegacy** [comment]
@xwcg ich hab gerade nochmal alle corridors und den engine raum exportiert, könntest du die nochmal reinholen? jetzt sollte es keine lücken mehr geben

**Comment by xwcg** [comment]
danke mache ich morgen!

**Comment by xwcg** [comment]
![image](https://user-images.githubusercontent.com/1357259/42246068-83a09a80-7f1b-11e8-84fa-af176328f65b.png)

wie im anderen issue schon, jetzt fehlt die tür zum hinterraum
