### ISSUE TITLE
Sputniks stecken in Türe fest

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#44]
Hab grade die Sputniks entdeckt, hatten aber mit vorliebe vor, sich im Türrahmen festzuglitchen bzw. darin zu spawnen:
![](https://puu.sh/APEYd/5e117b4200.png)

Müsste sich auch mit dem Block-Kollisionsding beheben, oder?

**Comment by evil-lemming** [comment]
Kann ich mich morgen (Dienstag) drum kümmern.

**Comment by xwcg** [comment]
wenn die sterben hängen die auch in der luft

**Comment by firoball** [comment]
vermutlich fehlt ein c_setminmax(). Das war beim Mopsen des EL-Codes noch ncioht drin.

**Comment by firoball** [comment]
Also das mit der Box ist schon korrekt gefixt. Ich schaue mir aber gerade noch den restlichen Sputnik Code an, da ich ihn noch auf die neuen Winkelfunktionen umstelle.

**Comment by firoball** [comment]
Ich schau mir das heute Abend nochmal an. Es scheint mit der Drehung (pan) zu tun zu haben. Das Problem haben prinzipiell alle Mobs.

**Comment by firoball** [comment]
Ich habe noch ein paar pohlsche Movement Hacks aus dem Playercode geklaut, und ich meine der Sputnik verhält sich nun besser...die Eselslerche aber glitcht leider rum wie zuvor. Ich weiß nicht, woran das liegt. Naja erstmal Commit und Bett.
Morgen dann endlich das Auge...

**Comment by firoball** [comment]
Bitte erneut testen, ob das jetzt besser geworden ist.
