### ISSUE TITLE
Insert battery sound/oder general insert item sound

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#49]

**Comment by ilegacy** [comment]
a sound for "door locked" would also be nice. i can't open any door in the game and i don't know if it's disabled in general or can be opened later via keycard.

**Comment by mk1x86** [comment]
er hat aber recht, dass man nicht weiß, **warum** die Tür nicht öffnet

**Comment by MasterQ32** [comment]
hm, wäre das vom aufwand überschaubei, bei versperrbaren türen noch ein locked-symbol irgendwie draufzumachen?

oder alternativ könnte man neben dem crosshair eine kleine interaktion anzeigen

**Comment by mk1x86** [comment]
Einfach verschiedene Sounds abspielen.
"Access denied, station is running on emergency power"
"Access denied. This area is restricted to level red personnel only"
"Access denied. This area is restricted to level blue personnel only"
...

**Comment by MasterQ32** [comment]
Okay, kann man natürlich auch machen, falls dir das vom Aufwand passt

**Comment by mk1x86** [comment]
ja, passt schon

**Comment by firoball** [comment]
Schön wäre natürlich auch, wenn kurz ein schloss angezeigt und wieder ausgefadet wird. Am 03.07.2018 9:21 vorm. schrieb mk1x86 <notifications@github.com>:ja, passt schon

**Comment by mk1x86** [comment]
Dank der großartigen Lisa haben wir jetzt eine tolle Stimme für das Schiff. Die "Access denied" Sachen habe ich mal eingecheckt, aber sind noch nicht im Code verbaut. @MasterQ32 vielleicht hast du ja Zeit, ansonsten mach ich das heute Abend

**Comment by firoball** [comment]
Was ich noch gut finden würde: Verschiedene Sounds einmal für Keycards/spezielle Items und dann für Standards wie Ammo/Medipack etc. Ich denke regelmäßig, ich hab aufgrund der Fanfare was tolles eingesammelt, dabei wars nur Munition. Nun... genaugenommen ist Munition ja auch was tolles... ach ihr wisst was ich meine :D

**Comment by mk1x86** [comment]
Ha, die sollte eigentlich auch nur für die Keycards sein. Muss ich noch trennen

**Comment by ilegacy** [comment]
Mal was anderes: Wie öffnet man die Türen eigentlich? Ich habe schon ein paar Keycards eingesammelt und sehe manchmal auch grauen Türen (die also ohne Keycard funktionieren müssten) aber ich habe noch nie eine gefunden die einfach mal aufgeht.  Muss ich da noch etwas drücken wie z.B. "E"?

**Comment by MasterQ32** [comment]
Q und E wechseln zur Zeit die Waffen, Benutzen liegt auf "F" (auch bei dem Terminal im Maschinenraum)

**Comment by mk1x86** [comment]
insert item sound existiert
