### ISSUE TITLE
Eis / Gefrierraum

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#50]
Das Eis im Gefrierraum soll nacher mit dem Flammenwerfer weggeschmolzen werden, hab ich das richtig verstanden?

Wenn ja, sollte der Flammenwerfer-Code dafür noch passende Infos ausspucken, die man vom Eis aus verwerten kann

Zudem: Das Eis hat noch Transparent gesetzt...
![](https://puu.sh/APGlV/86d7995cc1.png)

**Comment by mk1x86** [comment]
@MasterQ32 das Eis sollte in die Tür hineinschmelzen, sodass es immer weniger wird und dann gelöscht werden, bevor man die Tür öffnen kann

**Comment by MasterQ32** [comment]
Okay, hab mich mal drum gekümmert, das Eis schmilzt jetzt an der Türe weg, wenn man es mit dem Flammenwerfer anflammt
