### ISSUE TITLE
Whiskas.mdl mit externer Textur benötigt

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#52]
Die Textur vom Schädel ist leider intern gespeichert, und da dds, ist in MED kein Export und Umkonfigurieren auf extern möglich. Das dds File ist leider auch nicht im Repo abgelegt.

Ich muss die Skin mehrmals separat Meshgruppen zuweisen. Mit Kopien der internen Textur wird das sehr ineffizient.

**Comment by Hen-woll** [comment]
sollte noch in GitHub\LotterShock\ArtSource\enemie als head_fc.png gespeichert sein

**Comment by Hen-woll** [comment]
EDIT:
Whiskas verfügt nun auch über eine Stand Animation damit dies nicht zu statisch aussieht, ich würde es gut finden wen dies ins enemy verzeichniss eingefügt wird.

**Comment by firoball** [comment]
Sehr cool, DankeIch kümmere mich um den RestAm 03.07.2018 7:01 nachm. schrieb Hen-woll <notifications@github.com>:EDIT:
Whiskas verfügt nun auch über eine Stand Animation damit dies nicht zu statisch aussieht, ich würde es gut finden wen dies ins enemy verzeichniss eingefügt wird.

**Comment by firoball** [comment]
Ich habe die Stand Aniamtion als Approach Aniamtion verwendet. Das sieht noch besser aus.
Die Thematik mit den Meshgruppen habe ich verworfen. Von daher kann das hier zu.
