### ISSUE TITLE
Engine nach Tod und Levelneustart schon aktiv

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LotterShock#54]
Da muss wahrscheinlich eine Variable zurückgesetzt werden?

**Comment by xwcg** [comment]
ich hab grad gesucht wo die sinnigste stelle für das hier zu resetten ist:

`story_enginesEnabled = 0;
playerHasHazmat = 0;
playerHasDoubleJump = 0;`

aber ich hab nichts wirklich richtiges gefunden wo es eine "reset" funktion gäbe, also überlasse ich das mal wem der sich mit dem framework besser auskennt

**Comment by MasterQ32** [comment]
> aber ich hab nichts wirklich richtiges gefunden wo es eine "reset" funktion gäbe, also überlasse ich das mal wem der sich mit dem framework besser auskennt

game_open() wird zu beginn des Spiels aufgerufen und initialisiert das komplette spiel...
ich pack das da mal rein

**Comment by MasterQ32** [comment]
fixed in commit 6f9978379af7ad5d8cb1790f15f3f4f5deeb6fb5
