### ISSUE TITLE
Sputniks und Flammenwerfer = Infinite Splatter

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#56]
Im grunde was da oben steht, flammenwerfer und sputniks erzeugen unendlich viele splatter, sogar wenn sie tot sind

**Comment by MasterQ32** [comment]
Okay, man kann also Splatoon spielen:
![](https://puu.sh/APQtH/ca020a6469.png)

Kümmere mich morgen darum, die Sputniks brauchen nur nen cooldown timer

**Comment by firoball** [comment]
Nachfrage an dieser Stelle: Geht es nur um den FX Overload, oder generell um das gnadenlose wegmetzgern?
So wie ich das sehe hat nämlich der SPutik jetzt zwar einen Cooldown für den Splatter Effekt, nicht aber für seine Health. Hier müsste das Event gelockt werden.
Kann ich schnell erledigen, aber ich müsste wissen, was gewollt ist. 
Aktuell dürfte man bei höherer Framerate mit dem Brutzler häufiger Schadensticks verursachen, und killt damit schneller.

**Comment by evil-lemming** [comment]
Stimmt, daran hab ich nicht gedacht. Nach welcher Methode macht der Flammenwerfer überhaupt schaden? Macht jede Flamme einmal schaden oder machen die Schaden so lange sie existieren?

**Comment by firoball** [comment]
Habe das schon gefixt. Pushe ich nachher. Sputnik Code aktuell bitte nicht anfassen.
