### ISSUE TITLE
Auflösung ändern + Fullscreen

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#57]
Sollte auch irgendwann mal gehen, ich krieg augenkrampf in dem kleinen fenster

**Comment by MasterQ32** [comment]
https://github.com/Acknex/LotterShock/wiki/Settings sowie #27

**Comment by MasterQ32** [comment]
Auflösung live ändern sollte noch gehen...

**Comment by xwcg** [comment]
![shot_1](https://user-images.githubusercontent.com/1357259/42246543-484c97c0-7f1d-11e8-9e60-9c8eca5e652e.jpg)
![shot_2](https://user-images.githubusercontent.com/1357259/42246544-48684b50-7f1d-11e8-9e16-0aecb8ed773f.jpg)
![shot_0](https://user-images.githubusercontent.com/1357259/42246545-48938cac-7f1d-11e8-887c-a8a32e20e4d8.jpg)

das sind die verschiedenen dinge die ich sehe wenn ich im fullscreen die auflösung wechsle

**Comment by xwcg** [comment]
![shot_0](https://user-images.githubusercontent.com/1357259/42246579-6cc91524-7f1d-11e8-93d5-5becbfa45eec.jpg)
![shot_1](https://user-images.githubusercontent.com/1357259/42246580-6ce8d8dc-7f1d-11e8-8617-9f2debedc216.jpg)
![shot_2](https://user-images.githubusercontent.com/1357259/42246581-6d04a904-7f1d-11e8-9501-3a0c7211fa78.jpg)
![shot_3](https://user-images.githubusercontent.com/1357259/42246583-6d2a9830-7f1d-11e8-8e3e-84942ef9ec23.jpg)
![shot_4](https://user-images.githubusercontent.com/1357259/42246584-6d540d46-7f1d-11e8-8e39-2cf3c525598b.jpg)
![shot_5](https://user-images.githubusercontent.com/1357259/42246585-6d71031a-7f1d-11e8-8fc5-80653c0f0bd9.jpg)

Und das ist das ergebniss vom wechseln der auflösung im windowed mode

**Comment by firoball** [comment]
Wenn man im Spiel ist, sieht man nach einem Auflösungswechsel gar nichts mehr. Da fehlt wohl noch ein Rendertarget reset/lost für das Shader framework..?

**Comment by MasterQ32** [comment]
Abgesehen von HUD Change #102 sowie dem Shader-Foo tut auflösung ändern jetzt, ist auch im Optionsmenü einstellbar

**Comment by MasterQ32** [comment]
Habe das neu erstellen der Rendertargets gefixed, jetzt tut Auflösung ändern auch live.
commit be1a6533d8ea4b02b64ac68f1cae01de7083582b
