### ISSUE TITLE
Turret love

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#58]
Der Turret aus Teil 1 funzt wunderbar, allerdings bräuchte er nen passenden Shader. Die Skill41++ Settings habe ich mal in der Turret.c gelassen

**Comment by xwcg** [comment]
fände es toll wenn deine "test spawn" dinger nicht mit eingecheckt werden sondern nur lokal behältst, bzw die hinter nem define flag versteckst

**Comment by firoball** [comment]
Das ist Absicht so. Wenn die Sachen nicht platziert werden, dann finden sich beim Testspielen auch keine Schwachstellen.Am 03.07.2018 10:32 vorm. schrieb Michael Schwarz <notifications@github.com>:fände es toll wenn deine "test spawn" dinger nicht mit eingecheckt werden sondern nur lokal behältst, bzw die hinter nem define flag versteckst

**Comment by firoball** [comment]
matObject benötigt noch Support für Alpha Texturen @Slin

**Comment by firoball** [comment]
Habe mal einen Shader zusammengeworfen (turret.fx). Darf gerne angepasst werden.
Kann erstmal zu.
