### ISSUE TITLE
Maus-Cursor

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#60]
Habe gestern ne Runde im Vollbild gespielt und festgestellt, dass wir keinen Mauscursor haben... 

Möchte da jemand noch einen malen?

**Comment by Hen-woll** [comment]
siehe GitHub\LotterShock\ArtSource\hud [Cursor3.tga]

**Comment by MasterQ32** [comment]
Fixed in commit d0431e1bf8295f41640682b3754fe844a4d80690

**Comment by mk1x86** [comment]
sollte ander Farbe haben, nicht wie die Menüschrift rot

**Comment by mk1x86** [comment]
changed & close
