### ISSUE TITLE
Cheat [Flugmodus]

### ISSUE THREAD

**Issue by Hen-woll** [Acknex/LotterShock#62]
ich würde auch dieses jahr gerne einen kleinen Trailer zussamenschneiden, ich bräuchte einen Flugmodus der die Waffen und die Hudausblendet aber dennoch in der lage sein soll waffen aufzuheben. kann jemand dies für mich einbauen ?

**Comment by mk1x86** [comment]
Würde ich aber eh warten, bis wir fertig sind

**Comment by MasterQ32** [comment]
`idnohud` zum HUD ausblenden, `idfly` zum fliegen
