### ISSUE TITLE
Geländer in der Küche hat keine Textur bzw Test-Textur

### ISSUE THREAD

**Issue by ilegacy** [Acknex/LotterShock#63]
Ich kann das Geländer auch gern noch dazubauen und dann die Atlas-Textur verwenden. Soll ich?

**Comment by mk1x86** [comment]
klar, wieso nicht

**Comment by firoball** [comment]
Wie soll man überhaupt an die keycard gelangen? Seit das Geländer da ist, komme ich nicht mehr ranAm 03.07.2018 9:39 nachm. schrieb mk1x86 <notifications@github.com>:klar, wieso nicht

**Comment by ilegacy** [comment]
soweit ich weiß, soll man später einen super-sprung bekommen und mit dem kommt man dann hoch

**Comment by ilegacy** [comment]
küche + geländer nochmal exportiert. @xwcg  könntest du sie neu als mdl ins level einbauen? danke!

**Comment by xwcg** [comment]
![image](https://user-images.githubusercontent.com/1357259/42245946-0e6006f2-7f1b-11e8-9e3e-34bd54fd0775.png)

**Comment by ilegacy** [comment]
fixed. fbx ist hochgeladen.

**Comment by xwcg** [comment]
ist aktualisiert

@ilegacy den engine raum werde ich jetzt leider nicht neu importieren da ich schon massiv assets drin reingelegt habe und der aufwand zu groß ist das jetzt wieder neu zu sortieren mit den treppen

@firoball du brauchst erst die double jump boots. dann von einem tisch oder stuhl nach oben springen, eigentlich ganz easy

**Comment by ilegacy** [comment]
Funktioniert wunderbar :)

**Comment by MasterQ32** [comment]
Das Geländer im Maschinenraum ist auch noch kaputt:
![](https://puu.sh/ARwGd/4acc13e277.png)

**Comment by xwcg** [comment]
"kaputt"

das sind testgeländer aus portico  ca. 2005, die hatten noch nie eine textur, aber irgendwer kann da sicherlich eine drauf machen wenn er bock hat

**Comment by ilegacy** [comment]
fixed.
