### ISSUE TITLE
Flammenwerfer Performance

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#64]
Bei extensiver Brutzelung bricht die Framerate extrem ein. Evtl. kann man hier noch etwas optimieren.

Macht es vielleicht Sinn, "fake" Flammenpartikel ohne c_trace im Partikelevent für mehr Fluff zu spawnen?

**Comment by Slin** [comment]
Kommt drauf an ob der Fluff oder das c_trace das Problem sind ;) Overdraw vom Fluff kann nämlich auch ganz leicht für Probleme sorgen.

**Comment by MasterQ32** [comment]
Was wollen wir als Referenz haben? Ich kann gucken, dass ich das auf meiner intel 520 halbwegs vernünftig zum Laufen bekomme.
Was schade wäre, wenn man die Partikelzahl begrenzen müsste, aber die Traces und ähnliches sollten nur für die Flugzeit gelten, danach könnte es der Schadenscode sein...

**Comment by xwcg** [comment]
Kann man nicht einfach nur ganz wenige partikel "feuern"? Selbige emitten einfach weitere feuerpartikel die aber einfach nur partikel sind und sonst nix tun. Das würde auch helfen damit das flammen etwas lebendiger aussieht

**Comment by firoball** [comment]
Kannst ja einen Debugschalter einbauen, dann kann man ermitteln. Ich hab zwar nun beileibe nicht den mega Desktop, aber es bricht halt dennoch auf bis zu 10fps einAm 04.07.2018 1:19 nachm. schrieb Felix Queißner <notifications@github.com>:Was wollen wir als Referenz haben? Ich kann gucken, dass ich das auf meiner intel 520 halbwegs vernünftig zum Laufen bekomme.
Was schade wäre, wenn man die Partikelzahl begrenzen müsste, aber die Traces und ähnliches sollten nur für die Flugzeit gelten, danach könnte es der Schadenscode sein...

**Comment by MasterQ32** [comment]
Ich benchmarke das heute Abend mal und guck, dass ich die Perf irgendwie sauber hinbekomme. Vielleicht reicht es ja schon, die Größe der Partikel zu reduzieren

**Comment by mk1x86** [comment]
Habe sowieso das Gefühl, dass es an einigen Stellen manchmal was ruckelt

**Comment by Hen-woll** [comment]
der Flammenwerfer besizt  auch keine Animation wollte ich hierbei anmerken . ein leichtes zurückziehen der waffe würde das ganze dynamischer aussehen lassen.

**Comment by mk1x86** [comment]
Ich weiß nicht, wie aufwändig das ist, aber kann man die entity ptr nicht in nen ringbuffer schreiben und wenn zu viele da sind die alten löschen?

**Comment by MasterQ32** [comment]
> Ich weiß nicht, wie aufwändig das ist, aber kann man die entity ptr nicht in nen ringbuffer schreiben und wenn zu viele da sind die alten löschen?
Der Flammenwerfer verwendet für den Flammeneffekt ausschließlich Partikel, keine Entities... Ich hab aber grade die Vermutung, dass @Slin recht hatte bzgl des Overdraws

**Comment by MasterQ32** [comment]
Fixed in commit 4edc6d08a344249aa1f510721c33b93c12a771aa .
Ich Trottel hatte keine Bedingung mehr im Schadenscode

**Comment by mk1x86** [comment]
War leider zu trivial. Der Flammenwerfer macht keinen Schaden mehr

**Comment by MasterQ32** [comment]
Da war noch ein bisschen Fail im Code. Jetzt fixed: commit 6c8e6acb8a69fa30974a48fdb705643b0c6aedfc

Bitte um Close nach Verifikation

**Comment by mk1x86** [comment]
confirmed & closed
