### ISSUE TITLE
Pixelate Doom Retro Cheat

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#65]

**Comment by firoball** [comment]
Evtl. lässt sich dafür der Verpixelungsshader vom Morbisu Levelwechsel verwenden. Muss aber wohl in die Shader Pipeline reignewurstelt werden.

`float level_change_transition_progress_var;
float4 vecViewPort;

texture TargetMap;

sampler TargetMapSampler = sampler_state 
{ 
   Texture = <TargetMap>; 
   AddressU  = Clamp; 
   AddressV  = Clamp; 
}; 
    
float4 Transition(in float2 InTex: TEXCOORD0): COLOR 
{ 

	float factor = 100-level_change_transition_progress_var;
   InTex = lerp(InTex,round(InTex.xy*factor)/factor,level_change_transition_progress_var*0.01);
   float4 Color = tex2D(TargetMapSampler, InTex);
   float4 final = Color*(1-level_change_transition_progress_var*0.01);
   
   return final;
} 
 
technique DiffuseTechnique 
{ 
   pass P0 
   { 
      PixelShader  = compile ps_2_0 Transition(); 
   } 
} `

**Comment by ilegacy** [comment]
Im Grunde hatten wir das ja, indem das Textur-Filtering einfach deaktiviert war. Wenn wir die Textur so blurry lassen wie sie jetzt ist, dann haben wir zumindest auf dem Environment dicke Pixel :)

**Comment by MasterQ32** [comment]
> Evtl. lässt sich dafür der Verpixelungsshader vom Morbius Levelwechsel verwenden. 

Eher nicht, der ist nur für so level transitions geeignet:
![](https://puu.sh/ARvUo/f66fb4112d.png)

Ich glaube nicht, dass es ne sinnvolle Möglichkeit gibt, da View Entities leider nicht von PP beeinflusst werden :/

**Comment by firoball** [comment]
Naja es ist etwas sehr grobpixelig :D :D

Aber was Cheats betrifft:
Der Clipping Cheat heißt
idspispopd (Doom1) oder idclip (Doom2)

**Comment by firoball** [comment]
außerdem fehlt der Konami cheat.
oben oben unten unten links rechts links rechts b a (start)

:D

Wird beim Logo eingegeben. Aber ja... Future Release und so... dann könnte er irgendne gaga Difficulty freischalten.

**Comment by MasterQ32** [comment]
Ein Abfallprodukt der Outro-Entwicklung:
![](https://puu.sh/ATUnW/cfc6d615fd.png)

**Comment by xwcg** [comment]
perfekt!

**Comment by MasterQ32** [comment]
Naja, mal von der Waffe abgesehen ^^
Das ganze ist ein richtig billiger Tile-Shader, den ich für die Schriftsetzung der Matrix benutze, falls gewünscht, kann ich das aber noch als cheat einbauen, der dann alles verpixelt

**Comment by xwcg** [comment]
yes please :)
