### ISSUE TITLE
Keycard ist blau, Tür ist grün

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LotterShock#66]
! Keycard tauschen

**Comment by xwcg** [comment]
hab ich nicht gemacht

**Comment by mk1x86** [comment]
Kann sein, aber im Level muss die keycard ausgetauscht werden.

**Comment by xwcg** [comment]
es gibt nur 1 modell, die farbe wird per function zugewiesen

**Comment by mk1x86** [comment]
ne, ich hatte mehrere Modelle erstellt auf deine Bitte hin. Aber wenn du jetzt das benutzt, dann muss ich halt die Farben tauschen

**Comment by mk1x86** [comment]
btw, finale Version is up (credits)

**Comment by ilegacy** [comment]
Ist das Problem gelöst? Kann man das hier schließen?

**Comment by mk1x86** [comment]
nein. Die Karte muss im Level ausgetauscht werden

**Comment by firoball** [comment]
Jetzt sammelt man die blaue Card und bekommt die rote 🤣 

Ist es eigentlich Absicht (Easter Egg), dass man mit IDKFA ne blaue Karte bekommt, und die Tür ins Nirwana öffnen kann?

Oder kommt da noch was hin?

**Comment by mk1x86** [comment]
die blaue Tür sollte nicht blau sein, sondern grau (id 8 oder so)

**Comment by mk1x86** [comment]
Fixed in 4c124c5990ba0b9cc680757e8b64827823c778fb
