### ISSUE TITLE
   Balance is showing 00.0 when I imported the opening balances through a sql query in a Journal Entry. oddo10.

### ISSUE THREAD

**Issue by DonFeraRRi** [Acknex/LotterShock#69]
What I have done is, I entered Opening Balances in journal Entry through a sql query mentioned below.

insert into account_move_line (move_id,journal_id, company_id, account_id, operating_unit_id, partner_id, name, currency_id, debit, credit, date_maturity) values(18467,79,1,3,10,11091,'TN',21,25538.71,0,'2018-03-31');

Both debit and Credit are showing. Balance being a compute field should reflect automatically but its showing 00.0. Any Idea where I have been wrong in this case or what I need to do more to reflect the Balances.
--

**Comment by MasterQ32** [comment]
I really wonder how you got Zorro mixed up into a beautiful acknex game

**Comment by DonFeraRRi** [comment]
Sorry?

**Comment by mk1x86** [comment]
Looks like we ne to remove the repo from the public

**Comment by MasterQ32** [comment]
Hab mal ne restriction aktiviert:

> Limit to repository collaborators
> Enabled with 1 day remaining.
>
> Users that have not been granted push access will be unable to interact with the repository.

Aber ich denke, wir haben einfach n bisschen zu viel Aktivität, um unauffällig zu bleiben

**Comment by firoball** [comment]
This project is not a place for Zorro support. 
The correct palce asking Zorro questions is here: http://www.opserver.de/ubb7/ubbthreads.php?ubb=cfrm&c=1

Issue closed.
