### ISSUE TITLE
Beastiary Einträge

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#71]
Kannst du mal in der `bestiary.c` die ganzen Einträge proofreaden und ggf. mal aufpimpen, das ist grade nur von mir so n bisschen Debug-Blabla, der nicht mit der Lore konsistent ist

**Comment by mk1x86** [comment]
@xwcg noch irgendwelche Änderungswünsche? (da ist noch ein "beeing" statt "being", dass korrigiert werden müsste... summ summ summ, aber sonst sollte okay sein)

**Comment by xwcg** [comment]
ich hab mir die noch garnicht angeschaut
