### ISSUE TITLE
Corridor Re-Export

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LotterShock#73]
@xwcg Ich hatte alle Korridore ne exportiert. Nun haben sie ein paar mehr Lampen und sollte immer korrekt mit allen Teilen abschließen. Könntest du sie neu exporten?
Sag mal, kann ich nicht einfach FBX -> MDL machen und das einchecken? Oder musst du dann noch im Level irgendwas aktualisieren?

**Comment by xwcg** [comment]
kannst du auch.

**WICHTIG** schau dir vorher an welche Corridor datei die richtige ist!!! Beim allerersten export waren die stücke teils falsch benannt aber das ist mir dann erst viel später aufgefallen als ich das erste mal nach dem endstück gesucht habe. Deswegen sind die jetzt einfach so benannt wie sie sind und das muss beibehalten werden!!!

1. MED Öffnen
2. File -> Import -> Model from FBX
3. 2x OK Drücken (wenn er hier hängen bleibt, per Task Manager beenden und neu versuchen)
4. Schauen ob alles stimmt (Geometrie)
5. Jetzt erstmal im Game/Level ordner speichern (weil sonst die Pfade nachher absolut und nicht relativ sind)
6. Object -> Manage skins. Wenn mehr als 1 skin gelistet: gehe zu 6A. Wenn keiner gelistet zu 6B. Ansonsten zu 7. weiter.
6A. Die überzähligen skins auswählen und mit "Delete Skin" löschen bis nur noch 1 da ist. Weiter zu 6C
6B. "New Skin" Anlegen, weiter zu 6C.
6C.  Das Skin fenster etwas runter schieben damit du zugriff auf die toolbar bekommst. Mode->Group Mode wählen und sicherstellen dass du auch das "Select" tool an hast. Das gesamte modell auswählen und im Skin fenster den Skin auswählen, dann "Set Skin" drücken. Auswahl aufheben und schauen ob alles geskinnt ist.
7. Mode->Group Mode, Mode->Select, Alles auswählen, Edit->Groups Merge
8. Speichern

**Comment by xwcg** [comment]
kannst du auch.

**WICHTIG** schau dir vorher an welche Corridor datei die richtige ist!!! Beim allerersten export waren die stücke teils falsch benannt aber das ist mir dann erst viel später aufgefallen als ich das erste mal nach dem endstück gesucht habe. Deswegen sind die jetzt einfach so benannt wie sie sind und das muss beibehalten werden!!!

1. MED Öffnen
2. File -> Import -> Model from FBX
3. 2x OK Drücken (wenn er hier hängen bleibt, per Task Manager beenden und neu versuchen)
4. Schauen ob alles stimmt (Geometrie)
5. Jetzt erstmal im Game/Level ordner speichern (weil sonst die Pfade nachher absolut und nicht relativ sind)
6. Object -> Manage skins. Wenn mehr als 1 skin gelistet: gehe zu 6A. Wenn keiner gelistet zu 6B. Ansonsten zu 7. weiter.
**6A**. Die überzähligen skins auswählen und mit "Delete Skin" löschen bis nur noch 1 da ist. Weiter zu 6C
**6B**. "New Skin" Anlegen, weiter zu 6C.
**6C**.  Das Skin fenster etwas runter schieben damit du zugriff auf die toolbar bekommst. Mode->Group Mode wählen und sicherstellen dass du auch das "Select" tool an hast. Das gesamte modell auswählen und im Skin fenster den Skin auswählen, dann "Set Skin" drücken. Auswahl aufheben und schauen ob alles geskinnt ist.
7.  Skin auswählen,  "Skin Settings", sofern nicht gesetzt:  Häkchen bei "Texture" machen, "Texture File" ausklappen, "Extern" häkchen setzen, dann mit dem "..." die Atlas textur auswählen.
8. Mode->Group Mode, Mode->Select, Alles auswählen, Edit->Groups Merge
9. Speichern
