### ISSUE TITLE
JCL hi-res gefunden

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#74]
![ego3](https://user-images.githubusercontent.com/1357259/42267152-973498fa-7f78-11e8-8a96-7d0ec0204475.jpg)

vielleicht können wir die modelle mal mit nem frischen HD Gesicht versehen?

**Comment by mk1x86** [comment]
HOLY SHIT! Wo?

**Comment by xwcg** [comment]
http://www.financial-hacker.com/services/

**Comment by firoball** [comment]
Das ist creepy :D

**Comment by MasterQ32** [comment]
😨

**Comment by evil-lemming** [comment]
Dafür, dass er angeblich bald in Rente gehen soll sieht er auf dem Bild aber sehr frisch aus. Acknex-Entwicklung hällt wohl jung. Oder Nicht-Entwicklung lässt auch nicht altern.
Am besten finde ich seinen Avatar, der sieht ja genauso aus, wie das Zorro-Lotti-Model. ^^ Ok, Zorro sieht generell so aus, aber trotzdem...

**Comment by Hen-woll** [comment]
ich würde vorschlagen dies auf die ackcon 2019 zu verschieben für ein vollkommen neues Model ;) 
so sieht man unsere jährliche qualitäts steigerung . ich speicher das bild aber schonmal für alle fälle ab
