### ISSUE TITLE
Musik

### ISSUE THREAD

**Issue by MasterQ32** [Acknex/LotterShock#75]
Was haltet ihr von der Idee, auf Bandcamp oder ähnlichem ein Album mit den gesammelten Credits-Songs zu machen? Oder auch auf https://www.vksbm.de/ackcon/ als ZIP anbieten

**Comment by xwcg** [comment]
Gibts schon, müsste nur mal bei gelegenheit die neuen songs reinpacken;

https://acknex.bandcamp.com/releases

**Comment by MasterQ32** [comment]
Oh geil, wusste ich gar nicht... Das muss auf jeden Fall in die README rein

**Comment by mk1x86** [comment]
Da fehlt noch der Song vom letzten Jahr
