### ISSUE TITLE
Batterie und Batterieladestation

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LotterShock#76]

**Comment by mk1x86** [comment]
Die Batterie ist jetzt fertig und ist in der Küche im Storage platziert. hat die action "battery". Vielleicht kann
@MasterQ32  oder @firoball das mal mit Leben füllen?

**Comment by mk1x86** [comment]
Naja, man muss das Ding irgendwie aufsammeln können ;)
subsystem item, bla. Hab keine Ahnung, was ihr da zusammengeschrieben habt und lasse deswegen lieber die Finger davon

**Comment by firoball** [comment]
Was genau muss hier mit der Ladestation gemacht werden (Spieleraufgabe?). Wird dort die Batterie gefunden? Liegt die Batterie irgendwo rum und muss erst an der Station geladen werden? Das Wiki ist da auch recht kurz gefasst.
Ich habe ein ziemlich einfaches Modell für eine Ladestation gebastelt (habe aber keinerlei Problem damit, wenn jemand was hübscheres zur Hand hat), und dann irgendwie festgestellt, dass ich mir bezüglich der Aufgabenstellung nicht 100% sicher bin. 
Wo soll die Ladestation im Level platziert werden?

**Comment by mk1x86** [comment]
Die Batterie findet man schon in der küche

**Comment by firoball** [comment]
Ja.... Schon... Aber was genau soll da jetzt noch passieren, war meine eigentliche Frage

**Comment by firoball** [comment]
Von der Spielerführung her schließe ich, dass die Ladestation nicht mehr benötigt wird? Weil dann kann das hier imho zu.

> The guys from the engine room asked if they could store their spare batteries somewhere. \"Why not store them in the engine room?\" I asked. \"Because there is no storage room in the engine room!\" they say. Just chuck it in the corner! Why can't they just keep their engine stuff with the engines?! Anyway, the chefs said they can keep it in their storage closet. Because THAT makes sense.... Not!

Allerdings ist dieses PDA noch nicht platziert.
