### ISSUE TITLE
Balancing (war: Waffen-Balancing, plasma lanze schaden)

### ISSUE THREAD

**Issue by DragonKitten** [Acknex/LotterShock#78]
beim testen der lanze ist aufgefallen, dass nur maximal jeder dirtte schuss überhaupt schaden macht. bis ich durch das erste turret durch war hab ich den großteil meiner munition schon verbraucht 
vielleicht unverwundbarkeitszeit anpassen oder waffe langsamer schien lassen?
letzteres würde auch der animation zu gute kommen

**Comment by firoball** [comment]
Den Hit Cooldown gibt es primär wegen dem Flammenwerfer, damit der nicht insta röstet. Außerdem soll man die Hit-Animation nicht zum Spammen nutzen können, da sonst die Gegner wehrlos sind und einfach weggewatscht werden.

Beides widerspricht dem Verhalten einer Plasmagun, da müssen wir uns noch irgendwas überlegen.

**Comment by mk1x86** [comment]
ist eigentlich recht simpel, hit cooldown muss waffenabhängig sein.
Davon ab ist es okay, dass die Plasmagun den Gegner wehrlos macht, aber sie muss dann so schwach sein, dass man sich nicht auf mehrere Gegner gleichzeitig konzentrieren kann.

**Comment by firoball** [comment]
Dann muss der komplette Hit Code aller Gegner nochmal umgebaut werden... Derzeit werden einfach die Events deaktiviert für die Dauer eines HitsAm 05.07.2018 9:54 vorm. schrieb mk1x86 <notifications@github.com>:ist eigentlich recht simpel, hit cooldown muss waffenabhängig sein.
Davon ab ist es okay, dass die Plasmagun den Gegner wehrlos macht, aber sie muss dann so schwach sein, dass man sich nicht auf mehrere Gegner gleichzeitig konzentrieren kann.

**Comment by mk1x86** [comment]
Der cool down ist in den einzelnen Gegnern drin ?!

**Comment by firoball** [comment]
Exakt. Am 05.07.2018 12:21 nachm. schrieb mk1x86 <notifications@github.com>:Der cool down ist in den einzelnen Gegnern drin ?!

**Comment by mk1x86** [comment]
Okay, vielleicht gucke ich mir das heute abend noch an

**Comment by MasterQ32** [comment]
> Den Hit Cooldown gibt es primär wegen dem Flammenwerfer, damit der nicht insta röstet. 

Hättest du was gesagt, ich kann den Flammenwerferschaden an irgendwie drei Reglern einstellen (Anzahl Flammen, Anzahl Schadens-Ticks pro Sekunde, Menge an Schaden)

**Comment by mk1x86** [comment]
dann sollten wir das nehmen und die Begrenzung rausnehmen

**Comment by firoball** [comment]
Hit cooldown ist Mob Sache, und hat auch mit der Dauer der Hit Animation zu tun. War also schon vor dem Flammenwerfer drin und wurde nur noch beim Sputnik ergänzt. Ich halte es für den falschen Weg, den cooldown in den Waffencode zu basteln.Am 05.07.2018 3:52 nachm. schrieb mk1x86 <notifications@github.com>:dann sollten wir das nehmen und die Begrenzung rausnehmen

**Comment by mk1x86** [comment]
Aber es kann ja nicht sein, dass man fein aufgelösten Schaden hat und die Gegner das überhaupt nicht interessiert. Der Flammenwerfer ist momentan schwer nutzlos

**Comment by firoball** [comment]
Ich habe die Hit Cooldowns nochmal angepasst. Weiter runter sieht nicht wirklich gut aus. Es ist aus meiner Sicht besser, der Plasmi noch etwas Tempo zu nehmen und ggf. die einzelnen Schüsse etwas stärker zu machen.

**Comment by MasterQ32** [comment]
Ich hatte heute mal einen externen Testspieler ans Spiel gesetzt. Fazit:
Das Spiel ist extrem schwer geworden, ich selbst schaffe es lebend bis in den Eisraum, da aber nur noch mit 30 HP und keine Medikits verbleibend.
Der Testspieler kam ohne Anleitung bis in den Maschinenraum, mit Anleitung dann bis zum Biodome.

Der Skull macht auch imho viel zu viel Schaden für das Leben. Er hält 3-4 Schüsse mit der Schrotflinte aus nächster Nähe aus, macht aber irgendwas >= 28 Schaden, was ich etwas unverhältnismäßig finde.

Die Sputniks finde ich vom verhalten ziemlich geil, aber auch hier finde ich den Schaden zu hoch.

Bin dafür, dass wir das Leben und den Schaden der Gegner nochmal n bisschen reduzieren

**Comment by firoball** [comment]
Wie ist eigentlich playerseitig das Schadensmodell implementiert? Ich habe gesehen, dass diverse c_trace der Mobs rausgenommen wurden, ein Treffer wird also irgendwo anders detektiert (rein über Distanz?)
Vielleicht kann man die Schadenswerte zwecks tweaking auch zu den Healthwerten in die global.h packen.

**Comment by sgpohl** [comment]
Habe die Plasmawaffe jetzt mal langsamer und stärker gemacht, ist jetzt auf jeden Fall einsetzbar und vom Output vergleichbar mit den anderen Waffen.

Finde aber nicht dass die Waffe so wie sie it mega viel Laune macht, da fehlt iwie der Kick.

**Comment by firoball** [comment]
Ist an der Stelle aktuell noch was zu tun, außer dem finalen Balancing von Waffenschaden und Gegner-HP/Schaden? Ich glaube das hier kann erstmal zu

**Comment by firoball** [comment]
Da war ich zu voreilig. Das Schwert verhält sich noch immer seltsam.
Eselslerchen kann ich gar nicht hauen damit. Die explodieren vorher.

Im Turret Raum musste ich wie ein Irrer auf einen Turret einprügeln (hätte ich ohne Cheat nicht überlebt), und dann hab ich aber den Turret dahinter auch direkt miterledigt. Der dürfte eigentlich außer Reichweite sein...

**Comment by firoball** [comment]
Fürs Feeling der Plasmawumme würde ich tatsächlich den Speed wieder etwas raufregeln (aber nicht so schnell wie vorher). Auch wenn dann nicht jeder Schuss trifft. Dafür kann man ja dann etwas großzügiger mit der Munition sein.

**Comment by firoball** [comment]
@MasterQ32 kannst du dir bitte nochmal den Aim Code der Cellgun anschauen. Das Problem scheint nicht allein die Immunitätsphase der Mobs zu sein, sondern, dass man oft nicht trifft, obwohl man direkt auf den Mob hält. Fällt vor allem bei den Augen auf. Vermutlich kann man dann die Schussfrequenz auch wieder etwas steigern.

**Comment by MasterQ32** [comment]
Hab die Cellgun mal n bisschen angepasst, vom Feeling her ist es jetzt ganz gut, man trifft auf jeden Fall auch besser, die Immunitätsphase finde ich aber immer noch ein bisschen zu lang, wo kann man die denn einstellen?

**Comment by firoball** [comment]
Die ist individuell bei den Mobs im Hit state. Ist aber schon ziemlich runtergedreht. Siehe Flammenwerfer Ping, der sieht bei den Lerchen schon fast überzogen ausAm 04.08.2018 1:53 nachm. schrieb Felix Queißner <notifications@github.com>:Hab die Cellgun mal n bisschen angepasst, vom Feeling her ist es jetzt ganz gut, man trifft auf jeden Fall auch besser, die Immunitätsphase finde ich aber immer noch ein bisschen zu lang, wo kann man die denn einstellen?
