### ISSUE TITLE
Release und Test Builds erstellen

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#79]
Alle relativen Pfade auffinden und vernichten.
Alles was nicht in die WRS darf, nach Media schieben und Pfade daraufhin zurechttrimmen.
Buildskript zusammenschrauben.
Das ganze scharf machen.

Zuschauen wie alles explodiert.

**Comment by MasterQ32** [comment]
> Alle relativen Pfade auffinden und vernichten.
`materials.h` ist noch recht verseucht mit absoluten pfaden, können/dürfen shader in die WRS?

ich hab bei meinen `media_play`-befehlen (also `music_...`) relative pfade verwendet, muss das so oder sollen die auch nur dateiname sein?

**Comment by mk1x86** [comment]
Shader gehören in wrs.
media liegt außerhalb der wrs, kann so bleiben.

Ich glaube, wir sind da schon auf nem guten Weg.

**Comment by firoball** [comment]
Media darf relative Pfade haben, kommt ja nicht in die wrs. Shaderkram gab es bisher eigentlich nie Probleme, das schau ich mir dann ggf anAm 05.07.2018 9:40 vorm. schrieb Felix Queißner <notifications@github.com>:
Alle relativen Pfade auffinden und vernichten.
materials.h ist noch recht verseucht mit absoluten pfaden, können/dürfen shader in die WRS?

ich hab bei meinen media_play-befehlen (also music_...) relative pfade verwendet, muss das so oder sollen die auch nur dateiname sein?

**Comment by firoball** [comment]
Shader kann man noch preocompilen. Das war irgendwie etwas wurschtelig, aber es ging. Am 05.07.2018 10:46 vorm. schrieb Robert Jäger <robert@firoball.de>:Media darf relative Pfade haben, kommt ja nicht in die wrs. Shaderkram gab es bisher eigentlich nie Probleme, das schau ich mir dann ggf anAm 05.07.2018 9:40 vorm. schrieb Felix Queißner <notifications@github.com>:
Alle relativen Pfade auffinden und vernichten.
materials.h ist noch recht verseucht mit absoluten pfaden, können/dürfen shader in die WRS?

ich hab bei meinen media_play-befehlen (also music_...) relative pfade verwendet, muss das so oder sollen die auch nur dateiname sein?

**Comment by firoball** [comment]
Es published... es resourced... es läuft nicht.
Acklog hilft wahnsinnig viel. Ich hasse diese Engine mitunter... sehr.
Commit mit den Anpassungen für WRS kommt gleich angepusht.

> Log of A8 Engine 8.47.1 run at Thu Jul 05 20:47:21 2018
> XXX on Windows NT/2000/XP version 6.2 Build 9200
> Options -diag
> 
> 
> MM mixer opened
> DSOUND device opened
> DI interface opened
> Start Window opened(c) Conitec - www.3dgamestudio.com
> A8 Engine - Pro Edition V8.47.1 - Mar  9 2016
> Linking ...
> 
> Mouse found
> Lautsprecher (Realtek High Definition Audio) opened
> NVIDIA GeForce GTX 960 pure T&L device 1ff9 detected
> D3D device NVIDIA GeForce GTX 960 1ff9 selected.
> ackXinput.dll opened
> EYE__die: function not found
> input_original_proc_message: function not found
> pX_stats: function not found.......................................
> Running LOTTERVSTHEWORLD2.EXE.
> Main started at 0.176
> D3D_Init Window: 720x480 -> Window: 1x720x480x32
> Video memory found: 4093 MB
> D3D_Resize Window: 1280x720 -> Window: 1x1280x720x32
> def_startup started
> playerCheatHp_startup started
> Main loop at 0.543....
> 1st frame with 4093 MB at 0.544
> Loading credits data...
> node(0.000000)
> node(1.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> node(0.000000)
> node(2.000000)
> node(0.000000)
> node(0.000000)
> Media/intro.mp3 audio opened
> state transition from 0 to 5.
> state transition from 5 to 1.
> LevelInit at 5.381
> 13 entities 1 cameras 1 lights 0 sounds 0 paths
>  2 lmaps 3 textures 6 meshes 6 submeshes 192 faces...ok
> LevelReady at 5.762
> HEADRELATIVE sound: 1
> state transition from 1 to 3.
> Media/background.mp3 audio opened
> LevelInit at 7.045
> 505 entities 0 cameras 0 lights 0 sounds 3 paths
>  1 lmaps 1 textures 70 meshes 70 submeshes 1001 faces
> Nexus overflow at 41142208
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined
> Action matObject undefined...ok
> LevelReady at 8.277
> state transition from 3 to 4.
>

**Comment by firoball** [comment]
+++ACHTUNG+++

Name des Hauptskripts hat sich geändert (main.exe ist doof, renamen auch)

lottervstheworld2.c

**Comment by firoball** [comment]
Ich kann das Level zum Glück schonmal ausschließen. Es stürzt jedes Level ab, das nach Spielstart geladen wird.
Das scheint mit dem langen Laden nach Ausfaden des Loading... Panels zu tun haben. Woher kommt dieser Freeze eigentlich? Was wird da gemacht?

ich habe framework_update() testweise rausgeworfen, bringt nix. Das läuft noch was anderes Amok irgendwo

**Comment by firoball** [comment]
Woah gefunden... das war fies.

	hud_weapon_icon[WEAPON_SWORD-1] = pan_create("bmap = label_sword.png;",2);
	hud_weapon_icon[WEAPON_SHOTGUN-1] = pan_create("bmap = label_shotgun.png",2);
	hud_weapon_icon[WEAPON_CELLGUN-1] = pan_create("bmap = label_cellgun.png",2);
	hud_weapon_icon[WEAPON_FLAMETHROWER-1] = pan_create("bmap = label_flamethrower.png",2);

Sowas checken weder Publisher noch Resourcer, und in der hud_open knallt dann ne div/0 weil kein bitmap = width/height 0

#dankejcl
