### ISSUE TITLE
Man stirbt erst < 0 HP nicht <= 0

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#81]

**Comment by mk1x86** [comment]
Soll man erst UNTER 0 sterben? das macht irgendwie nicht viel Sinn

**Comment by xwcg** [comment]
nein, aber so ist es momentan

**Comment by firoball** [comment]
Interessanter Bug. Der Playercode scheint alles richtig zu machen. Ich tippe auf einen HUD Rundungsfehler (0.4 -> 0)?

**Comment by MasterQ32** [comment]
müsste man dann ja mit einem `displayedHealth=ceil(health)` lösen können

**Comment by firoball** [comment]
Kann ich nachher suchen... viel drignender ist, rauszufinden, warum das gepublishte Spiel (auch ohne WRS) nicht läuft, sobald man ins Level kommt... ich kreise das gerade ein
