### ISSUE TITLE
Turret-aim kann nicht nach oben/unten schießen

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#82]

**Comment by xwcg** [comment]
![shot_0](https://user-images.githubusercontent.com/1357259/42351304-852e1964-80b4-11e8-9135-93e0c3caa98f.jpg)

die brauchen nen kleinen offset nach oben, sonst sind die zu harmlos wenn die in einer senke sind ^^

**Comment by firoball** [comment]
weg damit.
