### ISSUE TITLE
Turret, bodentextur muss ausgeblendet sein

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#83]
sieht sonst einfach scheisse aus

**Comment by mk1x86** [comment]
ehrlich gesagt würde ich einen neuen Turret besser finden und den an die Decke klatschen. Das passt einfach nicht

**Comment by firoball** [comment]
Turrets haben keine Boden Textur mehr und können an die Decke geklebt werden. Sind jetzt als Fake Lichter getarnt. Erstmal zu.
