### ISSUE TITLE
PDAs/Journals haben noch keine tonwiedergabefunktion

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#86]
Prinzipiell wäre ich dafür, dass der music player verwendet wird und der journal eintrag statt der musik abgespielt wird, dann wieder auf die "Musik" wechselt

**Comment by MasterQ32** [comment]
Journale werden ab commit 62adbf1a63cebe6a58e8a979cb41de481ae3e6f8 wiedergegeben, hab aber vergessen, die Musik runterzudrehen...

**Comment by MasterQ32** [comment]
Habs grade mal getestet, die Lautstärke der PDAs vs. Musik ist so eigentlich ganz in Ordnung
