### ISSUE TITLE
Sputniks können übereinander klettern und in cheerleaderformation angreifen

### ISSUE THREAD

**Issue by xwcg** [Acknex/LotterShock#87]

**Comment by firoball** [comment]
Habe mal group und c_ignore eingebaut. Probier mal, ob das irgendwas besser macht, ich hab die bisher nicht zum stacken gebracht.

**Comment by xwcg** [comment]
tun sie immernoch.

im cryo raum sind jetzt jede menge, wenn du die tür auf machst und aggro ziehst und den durchgang blockierst bis die tür wieder zu geht, dann stacken die sich sehr zuverlässig

**Comment by firoball** [comment]
also ich krieg das nicht hin, dass sie aufeinander stacken. Scheint eher ein Stacken auf den Spieler zu sein. Aber da wird ein c_ignore auch nicht viel retten... sie soltlen primär gar nicht erst so nah an den Spieler rankommen... hmm...

**Comment by xwcg** [comment]
hab das problem jetzt länger nicht mehr gesehen, denke das ist damit beendet
