### ISSUE TITLE
Lücke in Crew Quarters

### ISSUE THREAD

**Issue by ilegacy** [Acknex/LotterShock#89]
Diese Lücke scheint nicht im Asset zu sein sondern eine ganz leichte Verschiebung des Türrahmens.

![image](https://user-images.githubusercontent.com/12360416/42348570-2be87ff2-80aa-11e8-9aaa-ab1fae5c7f99.png)

**Comment by xwcg** [comment]
ich seh grad, die haben das alle weil ich die copy-pasted habe

**Comment by xwcg** [comment]
fixed,

@ilegacy bitte, BITTE hör auf die atlas textur zu exportieren, oder wenn es unbedingt sein muss, dann resize die auf 256x256 oder kleiner. Jedesmal wenn ich im git pulle und die wieder groß da ist, stirbt mir der leveleditor weg.
