### ISSUE TITLE
Bild erst einfaden wenn Spiel geladen ist

### ISSUE THREAD

**Issue by ilegacy** [Acknex/LotterShock#90]
Derzeit sieht man für einen Moment diesen Bildausschnitt, könnten wir den BIldschirm evtl schwarz lassen, bis das Spiel komplett geladen und bereit ist?

![image](https://user-images.githubusercontent.com/12360416/42348630-704f3230-80aa-11e8-9599-ee1c98035e23.png)

**Comment by MasterQ32** [comment]
Ich könnte einfach die Wartezeit nach dem Spiel laden erhöhen und den Player verzögert spawnen... Ich mach das mal

**Comment by MasterQ32** [comment]
Habe einen Versuch der Verbesserung in commit 42fc17ffa3e1ef58a807ff428012ef23deef58a2 gemacht. @ilegacy, ist das so besser?

**Comment by ilegacy** [comment]
Ja das wirkt auf jeden Fall besser! Danke :)
