### ISSUE TITLE
Schädel fliegen nicht...

### ISSUE THREAD

**Issue by firoball** [Acknex/LotterShock#92]
...sondern haben nur unsichtbare Beine.
Ich kümmere mich die Tage drum

**Comment by firoball** [comment]
Schädel fliegen jetzt. Ggf. lohnt es sich, die Dinger nochmal neu zu platzieren.

**Comment by xwcg** [comment]
ich hab die schon alle recht hoch platziert weil ich mir nicht sicher war wie die dinger funktionieren, einfach um auf nummer sicher zu gehen ^^

**Comment by firoball** [comment]
Sie sollten nicht hinter Hindernissen stehen, da sie die Spielerhöhe zu erreichen versuchen. Dadurch hängen sie z.b. an KistenAm 09.07.2018 2:07 vorm. schrieb Michael Schwarz <notifications@github.com>:ich hab die schon alle recht hoch platziert weil ich mir nicht sicher war wie die dinger funktionieren, einfach um auf nummer sicher zu gehen ^^
