### ISSUE TITLE
Spielerführung

### ISSUE THREAD

**Issue by ilegacy** [Acknex/LotterShock#94]
Was noch nicht so recht klappt ist die Spielerführung - vor allem weil alle Gänge relativ gleich aussehen. Ich würde dafür stimmen, dass wir daher relativ "offensichtlich" arbeiten, da ein neuer Spieler komplett aufgeschmissen sein wird.

Ein Vorschlag wäre die Key-Card in der Küche hier hin zu plazieren, denn man kann sie extrem leicht übersehen. Selbst mit dem Wissen das sie dort ist, brauchte ich mehrere versuche um mit dem Double-Jump übers Geländer zu kommen und war mit nicht sicher, ob das wirklich der richtige Weg ist, bis ich es geschafft habe. Zumindes die Lage der Keycard könnte helfen, die ganze Situation etwas klarer zu gestalten:

![image](https://user-images.githubusercontent.com/12360416/42351366-e72bf67c-80b4-11e8-8a3b-167c2ba551b3.png)

**Comment by xwcg** [comment]
die küche hatte ich jetzt schon länger nicht mehr wirklich angefasst, aber das kann ich eben machen

**Comment by xwcg** [comment]
bewegt

**Comment by xwcg** [comment]
was ich irgendwann sowieso noch mache ist wegweiser in die gänge zu pflanzen und decals and die wände, damit die alle etwas anders aussehen, dann findet man sich auch besser zurecht

**Comment by MasterQ32** [comment]
Stretch Goal: Die Eselslerchen brauchen noch ein paar Glockenkessel als Futter im Biodome, grade weil die glühend echt fancy aussehen

**Comment by ilegacy** [comment]
@xwcg klingt gut! was ja richtig cool wäre, wenn die wände so streifen hätten wie in half life und dann zu den farb-türen deuten:

![image](https://user-images.githubusercontent.com/12360416/42351832-49ccd920-80b7-11e8-95cf-79f04086cf77.png)

aber ich glaube das wird ein bisschen zu aufwendig.

**Comment by mk1x86** [comment]
das müsste vor allem Teil der Textur sein eigentlich bzw. mit vertex colors oder so.

AFAIK hat @Hen-woll schon Schilder gemacht, die müssen nur platziert werden.

**Comment by ilegacy** [comment]
Ich kann von der Textur verschiedene Farb-Versionen anlegen. Was ich ungern machen würde: Dann jeden Raum nochmal für jede Farbe neu als MDL anlegen. Ich glaube das wird sehr schwer für das Level Design. Ich hätte zwei Ideen:

1. Decals verwenden um diese Farbstreifen an die Wände zu bringen
2. Ich erstelle eine Geometry die kurz vor der Wand schwebt (quasi ein Fake-Decal) und das müsste dann in den Gängen plaziert werden

@xwcg Was denkst du?

**Comment by mk1x86** [comment]
Ich glaube, ein paar Schilder sind einfacher. Wir sind schon wieder viel zu lange an dem Spiel dran

**Comment by firoball** [comment]
Alternativ gäbe es noch die Möglichkeit, dass wir eine Liste an erforderlichen Aktionen mit einem groben Zeitrahmen hinterlegen, und entsprechend bei Zeitablauf einen Tip geben. Die Logik dahinter ist aber vermutlich mehr Arbeit, als das Level "sprechen" zu lassen. Ist die Reihenfolge der Aktivitäten definitiv streng vorgegeben?
Wäre insgesamt wohl mehr ein Stretch Goal. Aber zumindest die Idee ist mal festgehalten.

Ist eigentlich geplant, dass es direkt bei Ankunft ein Briefing über die aktuelle Lage gibt?
"Power generator failed... blabla..." so dass man ne Grundidee hat, wonach man mal Ausschau halten sollte, und das Spiel nicht einfach nur losgeht?

**Comment by mk1x86** [comment]
Ja, jede Tür, die du öffnen möchtest, gibt dir den Hinweis ;)

Und nein, man weiß sonst nichts. Siehe Storytexte

**Comment by Hen-woll** [comment]
> AFAIK hat @Hen-woll schon Schilder gemacht, die müssen nur platziert werden.
genau richtig, da ich gerade eben sehe das neue schilder verwendet werden frage ich mich ob die alten Verworfen werden ?,

fals dies der fall ist, könnte ich die neuen Schilder mit einer neuen Textur belegen.

**Comment by MasterQ32** [comment]
Die Schilder sind ziemlich fancy und helfen definitv bei der initialen Orientierung

**Comment by ilegacy** [comment]
sehr cool! jetzt findet man sich wirklich besser zurecht! wirkt auch direkt glaubwürdiger :) super gemacht!

**Comment by firoball** [comment]
Ich denke das passt so. Kann zu?

**Comment by xwcg** [comment]
geht ja nicht nur um schilder, also erstmal auflassen

**Comment by xwcg** [comment]
Oder einfach ne schiffsansage "Ignition Battery Required".

Sorry war die letzten tage beschäftigt und konnte nicht weiter dran arbeiten, ich bin aber freitag abend wieder da

**Comment by mk1x86** [comment]
Part 3/4 (das, was schon mit dem TTS-System eingebaut wurde) fehlt noch. Schnitt ist echt ne Menge Arbeit :-/ und ich muss mal ins Bett

**Comment by firoball** [comment]
Batterie hab ich einen zusätzlichen Terminalscreen mit Möp Sound eingebaut. Muss reichen.

**Comment by firoball** [comment]
Im Serverraum gibts jetzt auch eine zusätzliche Färbung von Bett und Monitor, um die Deaktivierung sowie Aktivierung visuell darzustellen.

**Comment by ilegacy** [comment]
@firoball Ich hatte meinen beim Durchspielen nicht gefunden, kann aber sein, dass ich ihn übersehen habe. Ich glaube @mk1x86 weiß am besten wo die hinsollen?

**Comment by mk1x86** [comment]
Hat @xwcg verteilt. Keine Ahnung, wo die hinkommen

**Comment by mk1x86** [comment]
Ohne laufen die server nicht

**Comment by firoball** [comment]
gemeint war das powercore.mdl
Aktuell - so habe ich es verstanden - hat man ja einfach ein zweites, noch zu modellierendes Terminal, das man einmal anklicken muss, und die Sache ist durch.

**Comment by MasterQ32** [comment]
Ich finde den aktuellen Stand der Spielerführung ausreichend, man sollte jetzt immer grob wissen, was zu tun ist. Von mir aus kann das zu

**Comment by firoball** [comment]
Paar Schilder fehlen glaub nochAm 03.08.2018 4:20 nachm. schrieb Felix Queißner <notifications@github.com>:Ich finde den aktuellen Stand der Spielerführung ausreichend, man sollte jetzt immer grob wissen, was zu tun ist. Von mir aus kann das zu
