### ISSUE TITLE
Airlock opens/closes all the time

### ISSUE THREAD

**Issue by ilegacy** [Acknex/LotterShock#96]
The airlock animation should be ... not running, right?

![image](https://user-images.githubusercontent.com/12360416/42351589-1f34c548-80b6-11e8-80ce-bd7b388f7fcb.png)

**Comment by mk1x86** [comment]
needs airlock hallway as well (model exists) and airlock door counterpart on the other side

**Comment by ilegacy** [comment]
I'm not sure what you mean with "Hallway". As far as I know the room itself is the airlock and as soon as the animation stops and the airlock-door is closed all the time, it would be perfect, wouldn't it?

@xwcg Is it easy to just turn off the animation? Or is there something planned with the open/closing?

**Comment by mk1x86** [comment]
No, it wouldn't because you would immediately be sucked out into space.
Patchnotes is attached to Starlotti's ship and connected via a "docking hose". So yes, the airlock to Starlotti's ship should be closed.

**Comment by firoball** [comment]
wenn man weit genug Richtung Gang geht, wird außerdem der Gib Raum sichtbar.

**Comment by MasterQ32** [comment]
Fix in commit d06ae095816ad682403bbd3e213a7ad10a9f0eff.
Die Airlock schließt jetzt und bleibt dann geschlossen
